### ISSUE TITLE
Ability to clone existing exhibits

### ISSUE THREAD

**Issue by nowviskie** [performant-software/Neatline#145]
It would be nice if users could duplicate existing exhibits for re-editing/re-imagining, without having laboriously to add and edit every item again.  This would be especially useful in a classroom setting, where an instructor could create a base exhibit and ask students to re-work and extend it.

**Comment by nowviskie** [comment]
(Also, I'm lazy.)

**Comment by jeremyboggs** [comment]
This shoudl be easy enough to implement. It would need to amend the title and/or URL slug to avoid conflicts with other copies.

Would you also want to consider this a parent-child relationship? Or, provide some indication that an exhibit is a derivative of another exhibit, and link to that somehow?

**Comment by nowviskie** [comment]
I don't think it's necessary to preserve parent-child relationships or any enduring connection between the original and the derivative. 

It might be nice to provide a link to the original in the admin interface (for reference, in case credit really is due, in which case it would be on the deriv's creator to mention it somewhere in the public interface) -- but you wouldn't want to a force a public display. The deriv might have been created by the same author, just for convenience -- or the original could change radically or go away.

**Comment by EvanPHamilton** [comment]
Has any progress on this been made?

**Comment by dleisawitz** [comment]
Just voicing my strong support for this idea.  It would be _very_ useful!
