### ISSUE TITLE
Add an exhibit "duplicate" button

### ISSUE THREAD

**Issue by davidmcclure** [performant-software/Neatline#252]
We've gotten a number of requests for a feature that would make it possible to duplicate exhibits - to create an exact copy of an exhibit and all of its records.

This would make it possible to do a crude kind of version control on Neatline content without having to dip down to the level of database dumps. For example, if I have an exhibit that I've started working on, I might want to duplicate it to effectively "save" it before going in a particular direction, that may or may not pan out the way I want. We've also had instructors request this feature so that they can spawn off archival versions of exhibits before the start of a new class, so that they can access the state of an exhibit as it existed at various points in time.

Rough approach:
- Under the exhibit title in the browse view (where "Public View," "Exhibit Settings," etc.), add a "Duplicate" link.
- When this is clicked, spin up a background process that duplicates the exhibit (create new exhibit, then just run `$newExhibit->setArray($oldExhibit->toArray())`), and then pages through all of the records in the exhibit, duplicating each individually.

**Comment by waynegraham** [comment]
This looks like a duplicate of #145

**Comment by dleisawitz** [comment]
Just voicing my strong support for this idea. It would be _very_ useful!

**Comment by hlj24** [comment]
Hi friends, Just gave the Duplicate button a test while running Omeka 2.5.1. One click created 79 duplicates. Oops! Anyone else experience this?

**Comment by akstuhl** [comment]
Hi @hlj24, thanks for reporting this! If you have a chance, could you let us know what version number of Neatline you're using and any other plugins you have installed? Also, when Neatline created all those extra duplicates, did they all have the same name and did the name follow the format "[original exhibit name] ([username] copy)"?

**Comment by hlj24** [comment]
Hi @akstuhl, This occurred with Neatline 2.6.1, and all the duplicates had the same name and format as you describe. Other plugins installed: 
Carta
CSV Import
Embed Codes
Escher
Geolocation
HTML5 Media
NeatlineFeatures
Neatline SIMILE Timeline
Neatline Text
Neatline Waypoints
Omeka Api Import
UniversalViewer

**Comment by akstuhl** [comment]
Thanks, @hlj24 — we're taking a look at this and will follow up when we've been able to reproduce the bug.

**Comment by dleisawitz** [comment]
Where is the new duplicate function button located?  I'm very glad this is moving forward.

Thanks!
Dan

**Comment by akstuhl** [comment]
Hi @dleisawitz, the duplicate button (which was added in Neatline version 2.6.0) can be found among the links below each exhibit in the main Neatline admin view. Any exhibit you have permission to view should show a "Duplicate" link below its title along with "Public View," "Fullscreen View," etc. Clicking this will create a copy of the exhibit with "([your username] copy)" appended, on which you'll have full permissions.
<img width="506" alt="screen shot 2018-01-02 at 9 25 59 am" src="https://user-images.githubusercontent.com/2431978/34488677-05532aa0-ef9f-11e7-9a29-2e603623ec4f.png">

**Comment by dleisawitz** [comment]
That explains it.  It looks like I have Neatline Version 2.5.1 by Scholars'
Lab as a plugin on Omeka.  I'm going to check with the digital dept. on my
campus to see if I can upgrade to 2.6.

Thanks for your help!
Dan

**Comment by jeremyboggs** [comment]
This feature was added in 2.6.
