### ISSUE TITLE
Date centering in Firefox

### ISSUE THREAD

**Issue by waynegraham** [performant-software/Neatline#256]
There appears to be a Firefox-specific rendering issue for Timeline BC dates in a Neatline exhibit. For **startdate** -000100 and **enddate** -000080, the span exits, but does not move on the DOM. However, AD dates do appear to function properly.

Again, this _appears_ to be a Firefox only issue (testing on OS X 23 and 24), but functions as intended on other browsers I've tested (Chrome, Safari, and IE).

Current work-around is to use a different browser.

**Comment by jeremyboggs** [comment]
Moved to https://github.com/scholarslab/nl-widget-Simile/issues/17
