### ISSUE TITLE
Timeline gradients

### ISSUE THREAD

**Issue by waynegraham** [performant-software/Neatline#274]
The "fuzzy" factor for the timespans was removed...please put them back.

**Comment by nowviskie** [comment]
+1. I know our approach might not have been elegant from the development POV, but it's a key conceptual contribution and I don't feel like Neatline is Neatline without it.  Is there anything of immediate use in this new project? https://github.com/ComputingPlace/Topotime

**Comment by jeremyboggs** [comment]
@nowviskie Not sure it's of immediate use, but it looks like a nice alternative to Simile, for this and [NeatlineTime](/scholarslab/NeatlineTime).

+1 for this also.

**Comment by jeremyboggs** [comment]
Moved to https://github.com/scholarslab/nl-widget-Simile/issues/16.
