### ISSUE TITLE
Mastering Slugs

### ISSUE THREAD

**Issue by Breeshee** [performant-software/Neatline#287]
What are some strategies to potentialize robust interlinking between Omeka items and NL records? I'm fumbling with the slugs linking with developing html skills. What are the steps to link via slugs? The documentation is missing the magic key for me. 

Thanks, 

Bria

**Comment by waynegraham** [comment]
@Breeshee Are you trying to create a link from an Omeka item to a Neatline Exhibit? The system is designed to go in the opposite way by generating connections to Omeka Items when they're imported in to an exhibit...or are you talking about something else?

**Comment by Breeshee** [comment]
@waynegraham I'm meaning to use the slug function (I assume this is where linking is possible) to link between items/records within an exhibit for public view. 

A scenario would be I have a record that shows "Contentcontentcontent, Reference 1, Reference 2" I would like "Reference 1" and "Reference 2" to link to another record within the same exhibit.

**Comment by davidmcclure** [comment]
Hey @Breeshee - if I'm understanding correctly, I actually don't think there's a way to accomplish what you're trying to do with the out-of-the-box tools in the editor. Just to make sure I'm thinking about this correctly - basically, if you have "Record 1" and "Record 2" in a Neatline exhibit, you want to have a link in the "Record 1" content that would open "Record 2," as if it had been opened by a click on the map?

That would definitely be possible, but it would be a new feature - we would need to add a "router" to the public exhibit display that would activate records based on an `id` or `slug` parameter in the URL - eg, `/neatline/show/exhibit-slug#record/record-slug`.

Would that make it possible to accomplish what you're trying to do? Let me know, and if so I'll file a feature request.

Cheers,
David

**Comment by Breeshee** [comment]
Hi David,

Thanks for the response, and you are understanding my request properly: to
create hyperlinked connections between records within an exhibit but
navigable through the records themselves.

Please do file a feature request, and I'll watch for updates.

My best,
Bria

**Comment by Breeshee** [comment]
Hello David!

Do you have any updates on this feature request? It would be great to learn of a general timeline for when the router is built into Neatline. 

Thanks!

Bria

**Comment by waynegraham** [comment]
@Breeshee We don't have a timeline for implementing this feature request. We're a bit short staffed right now (David has taken a really cool new job) and it will most likely be fall before we are in a position to start evaluating feature requests and planning future releases.

**Comment by dcsoliday** [comment]
Any update on this? It's been about a year and a half.

I'm trying to do the same thing as Bria. We've got a map with more than one record referring to each location. We're trying to have one Neatline record with the spacial data to be displayed on the map, and that record will have links to the other records.

Any help would be appreciated.

**Comment by davidmcclure** [comment]
Hey @dcsoliday and @Breeshee, 

This was added last year, though looks like we forgot to close the issue. All records now get a distinct, hard-link-able URL. Eg: `www.exhibit-url.org#records/16`. So, if you've got records A and B, and want to link from A -> B, you could just put the link to record B in the "Body" field for record A.

See this exhibit for a demo - http://neatline.dclure.org/neatline/show/record-links-demo.

Best,
David

**Comment by dcsoliday** [comment]
Thank you so much for the prompt response, David.

That's what I've been using, but it hasn't been working. The URL changes to
reflect the new record ID, but the bubble doesn't show. ...it now seems
like that might be by design, as I've changed the spacial data for the
record we're linking to and it does actually zoom the map there. Is there a
way to also display the record's bubble when linking to it?

Our project is public (although hidden from site navigation until full
launch) at http://ciudadjuarezartandpoetry.org/neatline/fullscreen/main,
and you can go directly to a test record here:
http://ciudadjuarezartandpoetry.org/neatline/fullscreen/main#records/40.

I had posted a question about this on the Omeka discussion forums, but have
had no reply. If it should be asked elsewhere as a support question, please
let me know where.

David
