### ISSUE TITLE
Neatline Contigency

### ISSUE THREAD

**Issue by Breeshee** [performant-software/Neatline#296]
Hello!

Experimenting with Neatline has been a great educational experience. At the moment I am working on a project and am curious about the longevity of the Neatline Plug-in. Will developments in Neatline stagnate to its current working functions/format, or will there be investment in advancing its design, use, and features?

Please provide a realistic idea as a long term project is dependent on the mapping software that we will commit to. 

Thank you kindly, 

Bria

**Comment by waynegraham** [comment]
@Breeshee,

The Scholars' Lab is committed to this project, but one of the reasons we open sourced this (and just about everything else) is that should we become less-committed to a particular project, that there might be an open source community that would continue the work. This does require a different kind of commitment to these types of projects from people who want to use the software long-term than when you purchase off-the-shelf software, but we do hope that it commits to the more people being invested in the long-term usefulness of the software.

If you're really interested in the long-term of this project, we can talk more about how you might be able to contribute to the project in a meaningful way.

**Comment by tamielbr** [comment]
We've done some work helping out with bugs, and we're actively looking for some funding to continue working on our project (http://cultcampinas.org) which we hope can be reverted to more substantial contributions in terms of software design. 
Part of the reason for using Neatline is that (in layering with Omeka) it has features and capabilities which we are hard pressed to find in other mapping systems we've used. We've done some comparisons (some of the data needs to be verified) and perhaps this can help you decide (http://educacaoaberta.org/wiki/index.php?title=Sistemas_mapeamento).

**Comment by waynegraham** [comment]
@tamielbr That page is very useful! I did notice a couple things on it; Neatline does allow you to style both groups of shapes (including points) with the tags and CSS as well as have custom pointers (both as image markers) and as custom color points.

Mind if we find a place to link to this resource?

**Comment by tamielbr** [comment]
Not at all. Feel free to edit or let me know of anything that is wrong. We'll be "crowding" this within the next couple of weeks to get rid of initial mistakes. I'll get this one fixed.

**Comment by nowviskie** [comment]
This really is great! I updated the set of Neatline examples to include some more current ones (and remove "sandbox" links, which will eventually go away).

**Comment by tamielbr** [comment]
FIY, we've moved this to a new place.
http://dados.educacaoaberta.org/map_systems.html
