### ISSUE TITLE
Error saving item

### ISSUE THREAD

**Issue by tarsierspectral** [performant-software/Neatline#347]
When I link Omeka item to Neatline record, which only appears on Simile timeline and not on the map itself, I get an error stating "there was an error - the record was not saved". How do I resolve that issue? The moment I drop a random point on the map for that record everything is fine but I don't want that record showing on the map just on the timeline.

**Comment by davidmcclure** [comment]
Hey @tarsierspectral - Hm, I can't replicate this. What are the exact steps that you're taking? I did this:
1. Created a new exhibit with SIMILE enabled.
2. Created a record, activated is on the timeline, and set a start date.
3. Linked the item with an Omeka item.
4. Clicked "Save."

And the record saved without problems. I wonder if it could be some kind of non-standard data elsewhere on the record? Are you working with current versions of Neatline and Neatline Simile?

Best,
David

**Comment by tarsierspectral** [comment]
Hi David,

Neatline version 2.3.0
Neatline Simile version 2.0.2
Not sure what non-standard data I could have on the record.  The record just has start and end dates, they are -005000 for start date and -003000 for end date.  If I don't link to Omeka item then the record saves fine.  When I link it to Omeka item I get an error.  Or if I link to Omeka item and drop a point on the map (by going to the map tab in Neatline record and draw a point on a map) then the record saves fine too.  If I link to Omeka item and don't draw a point on a map then I get an error.  Does the Neatline record have to be on the map in order to link to Omeka item?

**Comment by davidmcclure** [comment]
@tarsierspectral - After you get the error, open up the developer tools in Chrome and click on the "Network" tab. You should see a listing in red for the failed request - click on it, and then click on the "Response" tab on the right. What's the output there?

**Comment by tarsierspectral** [comment]
Hi @davidmcclure, I have 4 listings in red.  I clicked on each of them and went to the "Response" tab and they all say "Failed to load response data".

**Comment by tarsierspectral** [comment]
I just created a new Neatline record and new Omeka item and I am experiencing exactly the same issue.  What else can I try?

**Comment by davidmcclure** [comment]
Hey @tarsierspectral,

Did this ever resolve itself? I still can't replicate the problem. Is this site online, or are you working locally? If it's online, shoot me an email, and maybe I can take a look at the exhibit.

**Comment by tarsierspectral** [comment]
Hey @davidmcclure, no this is still not resolved.  Yes, the site is online.  What's your e-mail?

**Comment by davidmcclure** [comment]
david at dclure dot org.

**Comment by davidmcclure** [comment]
Hey @tarsierspectral,

Ok, looks like this is a conflict with the Neatline Features plugin. Try this - deactivate Neatline Features, and then try to save the record, and I bet it will work. Are you using Neatline Features? If not, you could just leave it deactivated for the time being, until we fix the problem.

@erochest, here's the error:

```
Notice: Trying to get property of non-object in /plugins/NeatlineFeatures/lib/NeatlineFeatures/Utils/View.php on line 167

Notice: Trying to get property of non-object in /plugins/NeatlineFeatures/models/Table/Table_NeatlineFeature.php on line 187

Notice: Trying to get property of non-object in /plugins/NeatlineFeatures/lib/NeatlineFeatures/Utils/View.php on line 416

Notice: Trying to get property of non-object in /plugins/NeatlineFeatures/models/Table/Table_NeatlineFeature.php on line 187

Fatal error: Call to a member function getText() on a non-object in /plugins/NeatlineFeatures/lib/NeatlineFeatures/Utils/View.php on line 525
```

**Comment by tarsierspectral** [comment]
Hi @davidmcclure, I deactivated Neatline Features and it is saving now.  Thank you!

**Comment by waynegraham** [comment]
Closing this issue; this is a side effect of https://github.com/scholarslab/NeatlineFeatures/issues/81
