### ISSUE TITLE
Waypoints + Simile Timeline Date Range -- move to start date

### ISSUE THREAD

**Issue by hlj24** [performant-software/Neatline#348]
Hi,

I've looked around but haven't been able to find an answer to this question: Is it possible to change Neatline/Waypoints so that when a record is clicked in Waypoints the timeline shows the record's start date rather than to the middle of its range? I'm working with some date ranges that won't fit within the visible timeline even when the interval unit is millennia. Being able to show the start date instead of hte middle of the range would be very helpful.

Thanks!

**Comment by hlj24** [comment]
Oops. Don't want to duplicate #345 .

**Comment by waynegraham** [comment]
Closing this as a duplicate of #345

**Comment by hlj24** [comment]
Ty.
