### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by oeide** [performant-software/Neatline#349]
I read about searching for tags on the documentation page: http://docs.neatline.org/searching-records.html

The section includes the parenthesis: "(for more information about Neatline's tagging system, see the "Working with Tags" guide)"

However, there were no link to the "Working with Tags" guide and I did not find it anywhere in the documentation system.

**Comment by davidmcclure** [comment]
Hey @oeide - sorry about that! Looks like we folded the tags content into the "Editing Record Groups" section, and forgot to update this text. Until we fix the link, I think this is what you're looking for:

http://docs.neatline.org/style-tab-groups.html

**Comment by waynegraham** [comment]
@rondauva is this in the updates you have been working on?

**Comment by oeide** [comment]
@davidmcclure That is correct, thank you!

**Comment by rondauva** [comment]
Corrected the document reference in http://docs.neatline.org/searching-records.html. Wondering, though, if we should add links to the documents we're referencing in the documentation pages to make it easier for people to get to where they need to go. Will create a new issue for that and assign it to myself.
