### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by HeatherEason** [performant-software/Neatline#359]
I'm experiencing a serious glitch. When the colored circles are clicked on, an "item" from Omeka should appear, complete with metadata and a photo. Currently, only the title of the item appears. I've tried opening the project on different devices and in different browsers. I sincerely hope you can help me resolve this today; I am presenting at a conference tomorrow. 

My project can be reached with the following link:

https://chauceranditaly.library.utoronto.ca/neatline/show/liminal-representation-inferno#records/89

Thank you,
Heather Eason

**Comment by erochest** [comment]
I think that Ronda handled this in the Neatline email listserv, so I'm closing it.
