### ISSUE TITLE
Error editing entries/default map zoom

### ISSUE THREAD

**Issue by lrphoto4** [performant-software/Neatline#360]
I can create new records in Neatline, but once I've saved them once, any edits I make cannot be saved. 
Also, the map defaults to somewhere near Africa, I have tried setting the default to the location of my map in the Styles tab, but that will not save at all.
Several people have suggested permissions issues?

**Comment by erochest** [comment]
This looks very similar to [Error editing records and setting default zoom in Neatline](http://omeka.org/forums/topic/error-editing-records-and-setting-default-zoom-in-neatline). Would that be of any help.

If not, we have also had issues when servers are running [ModSecurity](https://www.modsecurity.org/). The post ['Forbidden' error when trying to add an item](http://omeka.org/forums/topic/forbidden-error-when-trying-to-add-an-item) suggests commenting it out of the Apache configuration if that is the case.

**Comment by davidmcclure** [comment]
Yeah, if the error just shows up when saving existing records, that does sound like the PUT problem. Maybe we should just use POST for everything, to avoid this?

**Comment by lrphoto4** [comment]
Thanks for the comments, it is working now!

**Comment by lrphoto4** [comment]
erochest - that looks similar because that is also me

**Comment by erochest** [comment]
I thought it might be, but I wasn't sure, since your user names were different.

Glad you got it worked out.
