### ISSUE TITLE
Server-side filtering of vector points by tag

### ISSUE THREAD

**Issue by sgbalogh** [performant-software/Neatline#361]
Hi all,

I've been working on a project with Neatline/Omeka that involves faceting Neatline records based on tag. David McClure has very graciously helped me out with issues regarding interaction with the Neatline API to do this in-browser, but he pointed out to me that the amount of vectors that I would like to have on my map (at the end of this project, it might be approaching 6 - 8k single points, spread across ~2k Neatline records) would force me to find a way to do this filtering on the server instead. In other words, instead of having the user's browser load all 8k points, the idea is that we would have to have the server respond to the user's facets, and only present the points corresponding to those facets, and within their current viewpoint.

David pointed me to this bit of code to indicate that the Neatline API should theoretically be able to do this: https://github.com/scholarslab/Neatline/blob/master/models/NeatlineRecordTable.php#L195-210

But as it stands right now, it looks like this is no longer something that can be implemented. Would it be possible to get support for this again?

Thanks! 
-s

**Comment by erochest** [comment]
Thanks for the bug report, @sgbalogh ! I'll go ahead and see what I can do with this.

But in the meantime, to add a bit more context, here's the pertinent part of the email chain from the Neatline Collab mailing list:

> What this means, though, is that with a set of records that big, you'll probably need to do the filtering on the server, not the client - instead of loading in all the records en masse, and then filtering them on-the-fly in the browser, you'll need to pass a set of tags to the records API, which will then return just a subset of records for display in the client. This was the thing that I recommended at the very beginning, but then realized we had taken out :)
> 
> The good news, though, is that all the logic is implemented on the back-end ([here](https://github.com/scholarslab/Neatline/blob/master/models/NeatlineRecordTable.php#L195-210)) - we'd just need to re-wire the Javascript API that exposes it.

**Comment by sgbalogh** [comment]
Hi @erochest –– have you had a chance to take a look into this issue at all? Just trying to get a sense if this will be a possible modification to the API, or if I'll have to look for a different solution. Thanks again!

**Comment by erochest** [comment]
Hi,
Sorry. I have started looking at it, but I haven't finished it yet. I should get a chance to pick it back up this week or the next. I'll keep you posted.

**Comment by erochest** [comment]
This should take care of it. I'll try to cut a new release next week.

**Comment by sgbalogh** [comment]
@erochest, thank you so much! On vacation now but will play around with it as soon as I get back. I greatly appreciate it.

**Comment by erochest** [comment]
Let me know how it goes. The release should be out when you get back.
