### ISSUE TITLE
Geotiff of 3D model "moves" when overlayed on Google Satellite

### ISSUE THREAD

**Issue by hlj24** [performant-software/Neatline#362]
Hi,
One of my students is experiencing an interesting problem. She exported a .tiff of a 3D model (as viewed from above) from SketchUp, georectified it in QGIS, and added it as a layer to a Neatline project. She is using Google Satellite as her base map. When she moves around the map or zooms in and out, the geotiff appears to move--as if it is elevated above the map. Her model was built on the ground plane, however, and anyway elevation information shouldn't (that I know of) have been transferred to the 2D tiff that she exported. We switched to other base maps and do not experience this problem except with Google Satellite and Google Physical. She very much wants to use the satellite image for her project. So I'm wondering if anyone else has experienced this or has any insight into why this might be happening. Thank you very much!

**Comment by erochest** [comment]
Hi,

We've seen something like this a few times, but we haven't been able to dig into it enough to figure out what's causing it exactly. We _think_ it might be because of how computers handle floating point numbers (decimals), such as are used in coordinates. As the numbers are rounded to the level of precision, errors can be introduced which might make the images appear to shift slightly.

Like I said, that's really our best guess at the moment.

Sorry we're not more helpful on this.

Best,

**Comment by davidmcclure** [comment]
Hey @hannahlj007,

Does this just happen when the map is zoomed very far in, to the highest 1-2 levels? Or does it happen regardless of the zoom level?

If it does seem to be tied to the zoom level, then the fix might be easy - I think Neatline is requesting more zoom levels than the Google satellite API will provide, which causes OpenLayers to shift the overlay without being able to pull in higher-resolution tiles for the base layer.

Either way, let me know!

**Comment by hlj24** [comment]
Hi David,

It was happening at the highest zoom levels. The student later removed the 3D images from her map, so I'm not able to see if changing zoom levels helps. I'll keep this in mind for the next project, though, and will see if limiting the highest zoom levels helps.

Thank you!

**Comment by davidmcclure** [comment]
Hey @hannahlj007,

Hmm, sounds like it's something else, then. Is the exhibit available online in a place I could look at it, by any chance?

Since this is specific to the Google layers, I wonder if this is related to [this issue](https://github.com/scholarslab/Neatline/issues/363#issuecomment-114191964), which appears to be caused by a change in the Google API?

**Comment by hlj24** [comment]
Hi David,

I've done a quick test exhibit for you to take a look at: http://dukewired.net/hj24/omeka23/neatline/fullscreen/3d-models-in-neatline#records/5. I notice two things:
1.  The projection changes at a certain zoom level in Google Satellite (this is the biggest problem). We're interested in using Satellite, though, because it's one of the few open source base maps that doesn't have labels.
2.  When zoomed in to between 3-1, clicking and dragging makes the objects appear to move. It's almost as if the image is hovering in midair.

I have also experienced the issue that you linked to-he and I are colleagues working on the same server. Since this is the first time that I've tried adding a WMS layer of this kind (transparent space between objects), I don't know if what I've observed above secretly happens all the time underneath solid images or if it's something new to Google layers.

**Comment by davidmcclure** [comment]
Ah, yes, looks like we're hitting two separate problems. The first, and I think the bigger issue, is that the Google Satellite API does, indeed, switch to a "45 degree" tile set when you zoom below a certain point, which messes up the alignment of the overlays. Google does this automatically, but, @erochest, I just noticed that it looks like OpenLayers exposes an option to suppress this:

http://dev.openlayers.org/apidocs/files/OpenLayers/Layer/Google-js.html#OpenLayers.Layer.Google.useTiltImages

So, that could be a really easy fix, if the new API still respects whatever flag OpenLayers is using?

The second issue - the "hovering" overlays - is the issue I mentioned before, where Neatline is trying to zoom in farther than the Google API supports. We should be able to fix this by dropping down the `numZoomLevels` that we pass into the layer constructors:

https://github.com/scholarslab/Neatline/blob/master/views/shared/javascripts/src/map/layers/Google/Google.controller.js#L40

I'd guess this is a shifting target in the API, too? I remember tweaking these in the past to fix this problem, but I may have just made a mistake. Either way, though, I think both of these problems are fixable!

**Comment by erochest** [comment]
Fixed as of 69955d1fd3a60ad94329a680e369cdec5f38df7b.
