### ISSUE TITLE
Google Map Tiles Don't Load 

### ISSUE THREAD

**Issue by mjvo** [performant-software/Neatline#363]
Have an issue with Google Map tiles not displaying on the initial load of an exhibit when a Google Map (of any type) is chosen as default base layer.  

If I use the map controls to zoom in or out they appear, however.

Initial load:
![initialload](https://cloud.githubusercontent.com/assets/607467/8270145/24b5370c-179e-11e5-91db-a4999dd57c54.png)

After Toggling Zoom:
![afterzoom](https://cloud.githubusercontent.com/assets/607467/8270148/39c79fea-179e-11e5-8540-57f9c23dcc50.png)

Issue does not occur when non-Google base layers are selected as the default.  

Clean install of latest Omeka and Neatline.  Same issue as http://omeka.org/forums/topic/neatline-newbie-google-maps-dont-display

**Comment by waynegraham** [comment]
This one is a bit on the crazy side. I can confirm this (kind of). With NLText enabled, when you go to any of the views, the from Google appears not to load. However, if you wait for about a minute, the request does actually (finally) load the map. On my machine, it's consistent around 1.2 - 1.3 minutes. 

The only red in the console is on the record extent in the neatline-editor when it cancels the XHR request. I wonder if recent updates to the JS engines and the really funky stuff OpenLayers has to do for Google base maps is getting in the way here. 

@mjvo Do you need to have Google base maps, or are the OSM maps satisfactory?

**Comment by davidmcclure** [comment]
Looks like Google changed the API in a way that breaks OpenLayers 2:

https://github.com/openlayers/openlayers/issues/1450

For the time being, sounds like we could just peg the Google API version in Neatline? ([Here](https://github.com/scholarslab/Neatline/blob/a8fd43f8bbdee822fa35358dae252223c8796bdb/helpers/Assets.php#L169).)

**Comment by erochest** [comment]
Sounds good. I should be able to get to this later this afternoon.
