### ISSUE TITLE
Phase out Google Base Maps

### ISSUE THREAD

**Issue by waynegraham** [performant-software/Neatline#364]
We've been getting a few more bugs due to the Google Maps API lately (#362 and #363 specifically). We know we need to make a migration to a new platform (either Leaflet or OpenLayers 3), and one of the drawbacks to moving to OpenLayers 3 is the lack of support of Google layers (see #315). I want to start a conversation about the pros and cons of deprecating the Google base layers, what their replacement could be, and how best to minimize the impact of people who have exhibits in Neatline.

I think some alternatives to investigate for these layers include:
- Mapbox
- Bing Maps
- OSM
- Yahoo Maps
- ArcGIS Online
- MapQuest (though I believe these come through OSM) 

If we need to keep Google base layers, we'll need to rewrite the editor to use Leaflet; if we can drop support for Google, we can update to OpenLayers 3. Otherwise we'll need to rewrite most of the editor for Leaflet.

**Comment by hlj24** [comment]
Hi, I wanted to see if you all have made any decisions/progress on this issue? We're continuing to experience issues with Google Maps working properly in Neatline. Thank you!

**Comment by danielebrox** [comment]
Mapbox and Bing could be good choices I think!

**Comment by jeremyboggs** [comment]
This has been addressed in the recent releases.
