### ISSUE TITLE
Neatline Timeline plugin use File instead of Item

### ISSUE THREAD

**Issue by tamielbr** [performant-software/Neatline#367]
I'm trying to plot a timeline where each element is a FILE and not an ITEM. Since they both use DC and have a "date" element, I thought it would pick up, but it doesn't seem to, even if I use the specific item number (#xxx). I'm trying to plot a single item as it changes over time with its pictures, and all of the images are a single Item.

**Comment by erochest** [comment]
Hi @tamielbr 

Just to clarify, you are talking about the [Neatline SIMILE](http://omeka.org/add-ons/plugins/neatlinesimile/) plugin, which works inside of Neatline, right? You're _not_ talking about the (unfortunately and confusingly named) [Neatline Time](http://omeka.org/add-ons/plugins/neatlinetime/) plugin, which doesn't require Neatline and creates stand-alone timelines without any maps. Am I understanding this right?

Thanks,

**Comment by tamielbr** [comment]
Hi @erochest - Actually I am talking about the "confusing" one ;) But I guess the idea would work for both.

**Comment by erochest** [comment]
Good thing I asked then. :)

We've been talking about needing a new release for that plugin. Unfortunately it will be next week before I can start thinking about it. In the meantime, I'll move this issue over to that repository.

Thanks,
