### ISSUE TITLE
Search of Neatline records not functioning

### ISSUE THREAD

**Issue by jenbartle** [performant-software/Neatline#369]
Hi all!
The Neatline Records search in the admin panel is not functioning in any of our 2.4.x instances of Neatline. [We 'just happen' to have 2.4.0, 2.4.1, and 2.4.2 all installed on different instances on Omeka 2.3.] There is no visible error thrown; the query seems to go through to the URL properly, but no results appear.
The Search function works as expected with other instances with older versions [Neatline 2.3.0 on Omeka 2.2.2] on the same server. We had a problem similar to this ages (two years) ago with a new release but I can't remember how it was resolved; it may have been related to CentOS.
Thanks!
Jen

**Comment by erochest** [comment]
Thanks for the report. I'll see if I can replicate this.

**Comment by davidmcclure** [comment]
Hey @jenbartle - Is this just when you search for a specific term, or is the default state broken too, when it (should) just list out all the records?

**Comment by jenbartle** [comment]
Hiya @davidmcclure! The default state seems fine (if I understand you correctly); all imported records appear properly before a search, but when I search for a known string, all the records will disappear and none are returned.

**Comment by djakacki** [comment]
Hello @davidmcclure. A faculty member and I are having the same problem. We're running Neatline 2.2.4 and Omeka 2.1.4 (we just tried to update Omeka to 2.3 but ran into some formatting problems so are trying to get that sorted.)  Here is the process as I replicate it:
1) Create New Neatline exhibit, using handdrawn map as baselayer image (not geolocated)
2) Create a New Record. Fill in Slug, Title, Body; draw polygon (saving record after each)
3) Click on "Link to Omeka" to add item. When I click on "Search Omeka Items" I get a message that it is "Searching" but just a spinning wheel. When I try to type an item title or tag or ID range, nothing changes. I've added a screenshot of a quick demonstration of what I'm getting. 

Any suggestions greatly appreciated!
Diane

![screen shot 2015-08-24 at 3 48 19 pm](https://cloud.githubusercontent.com/assets/3153933/9451068/71089c2a-4a7a-11e5-9159-bbb94746ae68.png)

**Comment by erochest** [comment]
Hi @djakacki , thanks for the extra info. I hope to dig into this issue some this week. It's the first week of classes, however, so we'll see how this goes.

**Comment by davidmcclure** [comment]
Hey @djakacki and @jenbartle,

Sorry for the delay with this. I think I actually just ran into the same problem with a project here at Stanford - I think it's something related to the PHP or Apache configurations. I'll investigate.

**Comment by erochest** [comment]
@davidmcclure , Where I'm at, it appears to have to do with the queries. I haven't figured out if the indexing needs to be changed or if there are other issues with the full-text search.

**Comment by erochest** [comment]
I'll get more time to look at it this week, too, so I'll keep you posted.
