### ISSUE TITLE
Image layer on top of existing tiles

### ISSUE THREAD

**Issue by tamielbr** [performant-software/Neatline#370]
I am trying to add a switchable image layer on top of an existing Neatline exhibit with georeferenced items.

When I add the URL to an image layer, it is visible, but with white space around it - no tiles. I don't see an option to switch say, between the image and a tile layer like OSM even though it is made available in the settings.

Finally, once the image layer is on (URL inserted on the exhibit settings) it seems to constrain the tile space and non of the points that I have inserted are within the navigable limits (e.g. one of the points is in GEOMETRYCOLLECTION(POINT(-5238700.2255714 -2620637.2707878), but the navigable space is much smaller than this and the constraints make it so panning stops at a certain point and nothing from the original exhibit is visible). 

It seems like I might be doing something the wrong way, any pointers?

**Comment by erochest** [comment]
Hi @tamielbr,

Using a base image in Neatline is really more for things that aren't maps. Base maps plus georeferenced images are better for dealing with maps. We explain the difference in the [Neatline exhibits overview](http://docs.neatline.org/exhibits-overview.html).

From what I can tell, it sounds like you want to use a georeferenced image. We have a series of blog posts talking about how to do that in some detail:
1. [Using Neatline with historical maps :: Part 1 – Georeferencing](http://neatline.org/2012/08/20/using-neatline-with-historical-maps-part-1-georeferencing/)
2. [Using Neatline with historical maps :: Part 2 – Transparency](http://neatline.org/2012/08/23/using-neatline-with-historical-maps-part-2-transparency/)
3. [Using Neatline with historical maps :: Part 3 – GeoServer](http://neatline.org/2012/08/29/using-neatline-with-historical-maps-part-3-geoserver/)

This does require using [GeoServer](http://geoserver.org/) which isn't nothing. But I think this is the best way to cover the uses that you describe.

**Comment by tamielbr** [comment]
Thank you - I had seen the documentation, but didn't understand the idea of "georeferenced image" which is clear now.
