### ISSUE TITLE
Neatline Simile Documentation Clarification. 

### ISSUE THREAD

**Issue by jackhistorynorton** [performant-software/Neatline#372]
On the documentation page (http://docs.neatline.org/working-with-the-simile-timeline-widget.html) for Simile, it indicates "The settings that control the timeline's appearance are found in the Plugins tab on the Neatline editor screen." But it doesn't say that to access the Neatline editor screen, one should click on the name of the Neatline exhibit. Many actions in Neatline have verbs to indicate action, such as "Delete," or "Import" or "Edit." The Exhibit name link is just a link, and it doesn't change color when scrolling over it, as other Omeka links often due. 

Suggestion: add a phrase to The settings that control the timeline's appearance are found in the Plugins tab on the Neatline editor screen, _accessed by clicking the name the Neatline exhibit._  

If possible, make the text of the Neatline exhibits change colors when scrolled over. This may be a function of the theme I'm using (Astrolabe) and not a Neatline feature at all. 

Thanks.

**Comment by waynegraham** [comment]
Thanks for this @jackhistorynorton. We can definitely add the sentence to the docs. We've shied away from doing much with the default UI in the main panels that rely on the Omeka admin theme (your public theme doesn't actually get applied to the admin panel), but I think it would be a good idea to have the text change in some manner on hover. Do you think something as subtle as an underlining the text on hover events would suffice?

**Comment by jackhistorynorton** [comment]
Wayne,

I’m teaching with Neatline right now. Despite my best efforts with text and screen shots to direct students to the editor, a couple were still confused. I’m going to do an explainer video to show the link.

On your end, yes, please, an underline link would be great. 

Jack

**Comment by rondauva** [comment]
The documentation has been updated with the recommended addition and the change pushed up to github.

**Comment by jackhistorynorton** [comment]
Ronda,

Wonderful. Thank you. 

Jack
