### ISSUE TITLE
Subsequent timeline record "bubbles" fail to load after first sucessful load

### ISSUE THREAD

**Issue by jenbartle** [performant-software/Neatline#373]
Hi--

In the admin and public views of my Neatline exhibit, the first click of a timeline record successfully loads a record bubble, but all subsequent clicks of other timeline records fail to load the corresponding record bubble. The url is successfully built with the new record#, and the record will load upon ("manually") triggering a reload via the address bar, but the reload is not triggered upon clicking any but the first ("first" = after initial load of the exhibit) timeline entry.

Clicking map points works as expected.

We're using the latest version of Neatline 2.4.2 on Omeka 2.3; this happens in Chrome 45.0.2454.85 and FFox 36.0.4 for Mac and also on PC.

Thanks!

**Comment by erochest** [comment]
Hi,

Do you have a link to this? Are there any particular items that it's happening or not happening on?

That information would help us track it down.

Feel free to email it to me, if you'd rather.

Thanks,

**Comment by jenbartle** [comment]
Dear Future: This issue was fixed by the SIMILE 2.0.4 upgrade. 
Thanks you guys!

**Comment by erochest** [comment]
You're very welcome!
