### ISSUE TITLE
Neatline Static Image layer not appearing

### ISSUE THREAD

**Issue by djohnstonleddy** [performant-software/Neatline#374]
Hello,

Omeka v2.3
Neatline v2.5.0

I was hoping build a sample Neatline exhibit based off of a static image layer. However the image editor does not display the image I point to for the base layer (links to image and exhibit below). I've also tried different images and links to images hosted on different sites none of which are working. 

Zoom level is only 3, spatial layer is off.

Static Image
http://cdigs.uwindsor.ca/omeka/files/original/ef8d00a7964183ac11039c32e422e0d3.jpg

Exhibit
http://cdigs.uwindsor.ca/omeka/neatline/show/sample-literary-map

**Comment by erochest** [comment]
Thanks for the bug report. I'll see if I can dig into this early next week.

**Comment by erochest** [comment]
Hi @djohnstonleddy ,

Looking into this, it could be an issue with your PHP settings. Can you (or whoever your server admin is) look at the settings for `allow_url_fopen`? This needs to be set on in your system `php.ini` file.

Thanks,

**Comment by jeremyboggs** [comment]
@djohnstonleddy If this continues to be an issue for you, let us know!
