### ISSUE TITLE
Displaying the record bubble when hard-linking to it

### ISSUE THREAD

**Issue by dcsoliday** [performant-software/Neatline#375]
Is there a way to have the record's bubble (Title & Body info, etc.) show up on the map when hard-linking to it? Neatline nicely zooms the map to the location of the record. We'd also like it to display its bubble.

Here's the Neatline Labs Hard-Links Demo: http://neatline.dclure.org/neatline/show/record-links-demo

Here's our development site example, a record with two links to other records: http://ciudadjuarezartandpoetry.org/neatline/fullscreen/main#records/13

When you follow the link from another website it displays the bubble. However, when you follow the link from another record's bubble, it only shows the other record's location on the map. If you then reload the page, it displays the bubble. We'd like to be able to have site visitors go from one bubble to another without having to go back to the blank map in between.

**Comment by davidmcclure** [comment]
Hey @dcsoliday,

This is a bug, which was actually fixed just a few days ago, though we haven't cut an official release with the fix. For now, download the zip archive of the develop branch:

https://github.com/scholarslab/Neatline/archive/develop.zip

Unpack the zip and replace the `plugins/Neatline` folder. Let me know if this fixes it.

-David

**Comment by dcsoliday** [comment]
Thank you!

I downloaded the zip, uploaded it to the server, expanded Neatline-develop
from it, renamed the Neatline folder to designate it as old, then renamed
the Neatline-develop folder to just Neatline. I then logged back into
Omeka, and went to the Plugins page. It said I had a new version (2.5.0)
and prompted me to upgrade. I clicked the button and now it has Deactivate
and Uninstall buttons instead. I went back to the Neatline exhibit and
tested it in fullscreen (which we're planning to use as the site home page)
and tried out the record links. ...and they still aren't displaying the
bubble. Try here
http://ciudadjuarezartandpoetry.org/neatline/fullscreen/main#records/13
or here
http://ciudadjuarezartandpoetry.org/neatline/fullscreen/main#records/40.
Is there anything else I should do?

It's still using a child theme of Astrolabe
http://github.com/scholarslab/astrolabe. We've only modified the field
order in the bubbles (and Omeka items.) Other info that might be pertinent:
System Omeka 2.3.1 PHP 5.4.43 (cgi-fcgi) OS Linux
2.6.32-504.23.4.el6.x86_64 x86_64 MySQL Server 5.5.46 MySQL Client 5.5.46
PHP Extensions Regular bcmath, calendar, cgi-fcgi, Core, ctype, curl, date,
dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap,
intl, ionCube Loader, json, libxml, mbstring, mcrypt, mysql, mysqli,
mysqlnd, openssl, pcre, PDO, pdo_mysql, pdo_sqlite, pgsql, Phar, posix,
Reflection, session, SimpleXML, sockets, SourceGuardian, SPL, sqlite3,
standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, Zend Guard
Loader, zip, zlib Zend the ionCube PHP Loader, Zend Guard Loader Plugins
ExhibitBuilder 3.2.1 HideElements 1.3 (inactive) ItemOrder 2.0.2
ItemRelations 2.0.2 (inactive) Neatline 2.5.0 NeatlineFeatures 2.0.5
NeatlineSimile 2.0.4 NeatlineText 1.1.0 NeatlineWaypoints 2.0.2
SearchByMetadata 1.2 SimplePages 3.0.6 SimpleVocab 2.0.1 Themes astrolabe
1.0-rc.2 astrolabe-cjap 1.0-rc.2 (current) berlin 2.3 default 2.3.1
neatlight-master 0.1 neatscape 1.0-rc.2 seasons 2.3

David

**Comment by davidmcclure** [comment]
Hey @dcsoliday,

It's working on my machine - try clearing the cache on your browser?

**Comment by dcsoliday** [comment]
Viola! That's much better!

Thank you so much for your help on the weekend. It's greatly appreciated.

Problem solved.

David
