### ISSUE TITLE
blank screen in Neatline editor

### ISSUE THREAD

**Issue by sylviachong** [performant-software/Neatline#376]
Hi! We're running Neatline 2.4.2, and we've been having issues as more students are logging in to work on their exhibits for finals.

Two students have reported that their projects have "vanished." In the list of Neatline exhibits, their exhibits are still there, with the proper number of items there. However, when they click on either the name of the exhibit (to edit it), OR the Public View or Fullscreen View of their exhibit, they get a completely blank page: no editor, no records, no nothing. (see attached screenshots)

![image](https://cloud.githubusercontent.com/assets/13816050/11734353/9797d766-9f84-11e5-86b9-df646007aecb.png)

![image](https://cloud.githubusercontent.com/assets/13816050/11734357/a15423ae-9f84-11e5-8697-2686c0a21530.png)

When I look at the source of the blank page, it appears to be OK (there's code there, looks similar to the code on a functioning exhibit.)

By the way, the blank page problem happens both for the student (when logged in as a Contributor) and for me (logged in as Super).

Please help! We're in the midst of finals and I feel terrible that students are losing their work!

Best,
Sylvia
(fellow UVA prof)

**Comment by davidmcclure** [comment]
Hey @sylviachong,

This looks like the Google Maps bug - https://github.com/scholarslab/Neatline/issues/363. (Google recently changed their API, which appears to break the mapping library Neatline is using.) As a temporary fix, if you change the "Default Base Layer" setting in the "Exhibit Settings" form to a non-Google layer, the exhibit should work again.

Let me know if this fixes it.

Best,
David

**Comment by sylviachong** [comment]
I was hoping the problem was as simple as that, but both exhibits that went blank are using their own custom images as base layers (and don't have any Google layers enabled).

**Comment by davidmcclure** [comment]
Ah, I see what's going on - I can replicate this by entering in an invalid URL to the "Image Layer" field in "Exhibit Settings." Maybe the images being used in these exhibits changed locations, or went offline?

**Comment by erochest** [comment]
Hey @davidmcclure ,

Is ImageMagick required to use image base layers? Looking at the data being loaded, it appears that the image is valid, but the data has null for its height and width.

**Comment by davidmcclure** [comment]
Hey @erochest,

We're using PHP's built-in `getimagesize()`:

https://github.com/scholarslab/Neatline/blob/master/models/NeatlineExhibit.php#L231-L240

Which, from looking around briefly, seems to require that the `allow_url_fopen` and `allow_url_include` flags to be enabled in php.ini.

**Comment by erochest** [comment]
That would be it, probably. Thanks for finding that. We'll see if that takes care of her problem and add it to the documentation.

Thanks, and have a great weekend,

**Comment by sylviachong** [comment]
OK, I was able to make the blank exhibit reappear by deleting the non-map static base image and using one of the pre-loaded map layers instead! I will look into what Ronda recommended, which is to check the php setting that controls whether opening images from URLs is allowed on the Binghamton servers.

Thanks for your help on this! Too bad about the image base layer -- my students were starting to use that very creatively, but I guess it broke their projects in the end.

**Comment by davidmcclure** [comment]
Hey @sylviachong,

Were the static image base layers working before, but then suddenly stopped working? If so, something is weird there, sounds like something other than the PHP configuration issue. Can you send me one of the image urls that the students were using?

Thanks,
David

**Comment by rondauva** [comment]
Hi @davidmcclure,

I set up a Neatline exhibit on our workshop site using this background image from the URL that Sylvia's students were using. You can see it http://workshop.neatline-uva.org/neatline/fullscreen/testing-for-s-wong. The login and password for the workshop site hasn't changed, if you want to go take a look there, as well.

The URL for the image is http://i67.tinypic.com/33lo50i.jpg.

FYI, we are one release back on the workshop site, so it doesn't exactly match the configuration of Sylvia's Binghamton site.

Ronda

**Comment by sylviachong** [comment]
Sorry about that -- I should have saved those URLs but at this point it was more important for my students to get access to their work.

This is what one student said (of the Boat People exhibit): I have attached the image I was using as my background and I got it from this website http://www.historymuseum.ca/cmc/exhibitions/cultur/vietnam/vilea07e.shtml. I uploaded it to tinypic because that was before I knew I could upload my own image directly to the site.  However, my blank exhibit happened after I tried to add an item (photo of Tiana's Grandmother) rather than use an online url. 

For the other student (on the "War By Other Means" exhibit), she used this URL for her base layer: http://m-static.flikie.com/ImageData/WallPapers/33829cc9c5a54dd0bad4abd9c4513677.jpg. I just tried it again (put it back using Exhibit Settings) and it made her Neatline blank out again. Problem went away when I deleted the URL again.

Best,
Sylvia

**Comment by sylviachong** [comment]
P.S. I also tried the URL http://m-static.flikie.com/ImageData/WallPapers/33829cc9c5a54dd0bad4abd9c4513677.jpg on a completely new exhibit and it broke that exhibit as well. Tried a few other random image URLs and they also break my test exhibit on the Binghamton site. More evidence that the bug is in the static image base layer, and not anything else in the exhibit.

**Comment by rondauva** [comment]
Hi Sylvia,

Can you give us more information about the image the student tried to upload, please? Were they adding the image to Omeka? What size, in pixels and in MB was the image? Can you send me a copy of this image so that I can try some experiments here, please?

I've just created a Neatline exhibit with the  static.flickie.com URL from above as a background, and it's working fine on Chrome, Firefox, and Safari 9.0.2 from our workshop/testing site.

Which browser are you and your students using to access these exhibits? Safari 4.x and older renders javascript in a completely different way than the others and may be the issue, if that's what you're using.

**Comment by erochest** [comment]
Hi,

Another thing that might help would be to replace the background image in the exhibits that were effected, if the students have their information out. That way we can at least see what data is being sent back and forth on an exhibit that's currently broken.

Thanks,
Eric

**Comment by rondauva** [comment]
Problem was successfully recreated by disabling the allow_url_fopen and allow_url_include flags in php.ini on all versions of neatline. Dr. Chong has been notified with a request that she have the Binghamton IT admins enable those flags for her omeka installs. 

Closing this issue, but can reopen if further information is forthcoming.
