### ISSUE TITLE
CKEditor files not included in 2.5.1 release

### ISSUE THREAD

**Issue by davidmcclure** [performant-software/Neatline#381]
It looks like the CKEditor source files aren't included in the 2.5.1 tag - just the Neatline payloads. Here's what it looked like in 2.5.0:

https://github.com/scholarslab/Neatline/tree/61244ac1fc84aa878600e23ae9d3999db000ee32/views/shared/javascripts/dist/production

And in 2.5.1:

https://github.com/scholarslab/Neatline/tree/c377fb593f486e2c6e66a3a5c8900707a34871c8/views/shared/javascripts/dist/production

Not sure if CKEditor made it into the zip archive on omeka.org, but this breaks deploy-from-git flows with Capistrano, Ansible, etc.

**Comment by erochest** [comment]
Thanks for catching this. I'll see if I can cut a new release this afternoon.

**Comment by erochest** [comment]
Odd. The files made it into the zip archive.

I've re-committed them and reset the 2.5.1 tag, though, so this should take care of the deploy-from-git scenarios.

Fixed in f9b219c3253b84586e0f40f84e68aa24ee1afb1c

**Comment by davidmcclure** [comment]
Weird, thanks Eric!

**Comment by erochest** [comment]
Sure! No problem
