### ISSUE TITLE
Google Hybrid Layer doesn't work (blank map)

### ISSUE THREAD

**Issue by danielebrox** [performant-software/Neatline#382]
Hello,
we use Omeka 2.2.2 and Neatline 2.3.0.
Since august 2015 we experienced problems with the Google Hybrid layer.
All the exhibits we have done with Google Hybrid as the base map result in blank exhibits.
Sometimes, changing the base maps in Google Satellite and then coming back to Google Hybrid let the issue temporary disappear, till the next time you'll open the exhibit.
Those are few of our exhibit:

http://greatwarproject.eu/neatline/fullscreen/progetto-terra-scuola-tecchio
http://greatwarproject.eu/neatline/fullscreen/leomajor-pn-grande-guerra-confine-orientale
http://greatwarproject.eu/neatline/fullscreen/cornuda-e-maser-ww1

Thank you in advance for your help!

**Comment by erochest** [comment]
Thanks for the bug report. I'm looking into it.

OpenLayers has trouble with Google layers in general, and hopefully in the future we'll have the bandwidth to look at other options. I'll see if I can come up with a work-around in the meantime.

**Comment by danielebrox** [comment]
Thank you! We are running lot of workshops in schools so a work-around will be very appreciated! Thank you very much!

**Comment by danielebrox** [comment]
Update: Upgrading Neatiline to the version 2.5.1 and Omeka to version 2.4 the problem seems to be solved. I'll keep you posted.

**Comment by erochest** [comment]
Oh, great. I thought I testing upgrading, but maybe I only meant to.

**Comment by ewilloughby** [comment]
I am experiencing this same issue with Omeka 2.4 and Neatline 2.5.1 on a fresh install and didn't want to make a new issue unless you would like me to.  Hybrid maps nor streetmaps will load unless satellite is viewed first.  This may be an issue with Google Maps API v 3.20 being used with Open Layers version 2.13.1.  Google Maps 3.20 is retired as of Nov 2015 or so.  Found info on this thread on stackoverflow, the original solution stopped working and more info is in follow-up answers. http://stackoverflow.com/questions/32698848/openlayers-2-13-1-with-google-maps
