### ISSUE TITLE
Neatline Maps Removal

### ISSUE THREAD

**Issue by milnerm** [performant-software/Neatline#384]
Hello - not sure if this is where you're tracking this kinds of issues. We had a problem with an Omeka install, and while we managed to get it fixed and upgraded, it was clear that Neatline Maps was no longer needed. It didn't uninstall 'cleanly' though, and we're left with a missing plugin, and some tables in the Omeka DB that I'd like to deal with manually, if possible.

From what I can see, I can remove the NeatlineMaps record in the omeka_plugins table. But should I also remove the following tables as well? are they needed for any other Neatline plugins (we've got the rest of them chugging along). The tables only contain one record for Geoserver in between them, so I'm assuming that they're not needed for WMS links etc.

omeka_neatline_maps_server
omeka_neatline_maps_service

just cleaning house - some pointers would be great, thanks!

**Comment by erochest** [comment]
HI @milnerm 

Yes, if you don't need those tables, you should be able to drop them without any problem. From Omeka's point of view, the main thing that you'll need to delete is the record in omeka_plugins.
