### ISSUE TITLE
point image not showing

### ISSUE THREAD

**Issue by aherman49** [performant-software/Neatline#385]
Hi, I'm using Omeka 2.4 and Neatline 2.5.1 -I'm trying to add a point image to a neatline record and I can't get it to show up. The file address I'm using is http://omeka.bard.edu/files/original/a29031bd8b034ee58a78f2598196c925.png this image comes from the same Omeka instance that the Neatline exhibit is in. I've been able to do this in the past with other similar Omeka images but none are working currently. I've tried other .png files I found online as well with no luck. Any thoughts?

**Comment by davidmcclure** [comment]
Hey @aherman49,

When you click on that link, does the image come up in the browser? For me, the request times out. That's likely the reason - if the image isn't accessible over the web, Neatline can't pull it into the exhibit. Perhaps something's awry with Apache? Does the rest of the Omeka site work?

But, since it's also not working for other images - any chance the "Point Radius" or "Fill Opacity" fields have low values, near zero? That would cause the image not to display, even if it's getting loaded.

Let me know!
David

**Comment by aherman49** [comment]
Hi David, thanks for the email.  I can see the image when I click on it, but our Omeka install is behind a firewall. The rest of the site seems to work fine so not sure about an Apache issue.  I tried it again with another random image I found online but still no luck.
I tried setting the point radius to 200, and the fill opacity to 1. Here is the last image I tried: 

https://upload.wikimedia.org/wikipedia/commons/a/a1/1915-S_$50_Panama-Pacific_50_Dollar_Octagonal_(obv)_transparent_background.png

Thanks for your help!
Amy

----- Original Message -----

**Comment by aherman49** [comment]
Hi again,

So I tried recreating my Neatline exhibit on my Acu-gis/geoserver installation, as this install is not behind a firewall.  This one is running Omeka version 2.3.1 and Neatline 2.4.2.  I made the exhibit public so you can see it: http://bardgeoserver.net/omeka/neatline/show/germantown-1740-and-1980.  I tried making a point image record with the sample png provided in the Neatline instructions: https://www.google.com/images/srpr/logo11w.png.  I still don't see it on my map. I'm not sure what is going on, everything else seems to be working fine.  Any more suggestions?

Thanks!

Amy

----- Original Message -----

**Comment by davidmcclure** [comment]
Hey Amy,

Looking at the requests being made by the page, I don't see anything to that image, so it looks like the record isn't even getting displayed on the map?

This is hard to debug from without - if you send me login credentials at dclure at stanford dot edu, I'll go into the admin and look at how it's configured.

-David
