### ISSUE TITLE
Google Hybrid and Roadmap Basemaps Don't Display

### ISSUE THREAD

**Issue by ewilloughby** [performant-software/Neatline#386]
I am experiencing this same issue with Omeka 2.4 and Neatline 2.5.1 on a fresh install.  There was another issue ticket that reported this, but it has been closed and the solution does not work. I am reporting again as hybrid maps nor roadmaps will load unless satellite is viewed first. This may be an issue with Google Maps API v 3.20 being used with Open Layers version 2.13.1. Google Maps 3.20 is retired as of Nov 2015 or so. Found info on this thread on stackoverflow, the original solution stopped working and more info is in follow-up answers, which claim that a new version of the openlayers.js that isn't on the CDN fixes this issue.  http://stackoverflow.com/questions/32698848/openlayers-2-13-1-with-google-maps

**Comment by DavidGhedini** [comment]
I've tried the updated neatline-public.js and the issue still persists.

**Comment by jamiefolsom** [comment]
Hi @willo1ej and @DavidGhedini, this is fixed in the master branch, via #410. The next release will include the fix. Thanks for the report!
