### ISSUE TITLE
Clicks don't zoom

### ISSUE THREAD

**Issue by erochest** [performant-software/Neatline#389]
The problem is that clicking on an item in the public site ignores the current viewport default option unless the item is also a waypoint.

From @davidmcclure 's explanation in an email:

> This is actually the intended behavior! Though, in retrospect, it was probably a mistake. The reasoning was this - there are times when automatically focusing the map in response to a click on the map can be disorienting. Eg, say there's a "point" record, with a really focused-in default zoom level. If the user is panning around at the level of the country, and clicks on a point, it can be confusing when the map instantly zoom really far down - the user has to manually zoom back, find their previous area of focus, reorient themselves, etc. 
> 
> But, there are also lots of cases where you _do_ in fact want this to happen, and I think they outnumber the cases where you don't. Unfortunately, this isn't configurable in the UI. But, changing this in the code would be very trivial - just this line would have to be removed: 
> 
> https://github.com/scholarslab/Neatline/blob/master/views/shared/javascripts/src/map/map.controller.js#L80

**Comment by jeremyboggs** [comment]
Close this, until we get more demand—with examples—to justify changing the behavior.
