### ISSUE TITLE
WMS Base Layers Not Appearing

### ISSUE THREAD

**Issue by hlj24** [performant-software/Neatline#391]
Hello! It seems that we are not able to embed WMS layers as base layers in Exhibit Settings at the moment. We've tried on multiple servers, each with a different Omeka/Neatline version installed. We're also noticing that Neatline exhibits that used to have WMS base layers are no longer displaying their layers. WMS layers do, however, still appear when embedded in individual Neatline records. Some examples:

Omeka 2.2.2 + Neatline 2.5.0 = http://dukewired.net/omeka/neatline/show/vv-workshop-test
Omeka 2.4.1 + Neatline 2.5.1 = http://wired.dukedh.org/omeka/neatline/show/test

Any clues as to why this might be?

Thanks!!

**Comment by waynegraham** [comment]
Hi,

I just took a quick look and I think you're WMS address is wrong. Try these settings:

`http://dukewired.net/geoserver/wms`
`Venice:1729Ughi`

I believe there's a double reference to the Venice WMS namespace (in the WMS URI and the layer name). You should also be able to keep the WMS line `http://dukewired.net/geoserver/Venice/wms` and remove the `Venice:` from the layer name. This is kind of a quirky thing in Geoserver...

**Comment by hlj24** [comment]
Hi Wayne,

Thanks for this. My apologies - I am only just now returning to this issue. Interestingly, our lazy copy-pasting of the WMS address with the WMS namespace in both address and layer used to work, though trying to view exhibits with these base layers now I see that they no longer appear. In the examples I sent, I tried removing the double reference to the namespace. This causes layers embedded in individual Neatline items to appear. However, they still do not appear when added as base layers in Exhibit Settings. Initially, I thought maybe it was our geoserver.

Then I tested this problem out with another geoserver we use, and the base layer does appear in a test exhibit made in November 2015 (Omeka 2.2.2 + Neatline 2.5.0): http://dukewired.net/omeka/neatline/fullscreen/st-chiara-test-overlay. But the same base layer will not appear in a new installation of Omeka/Neatline (Omeka 2.4.1 + Neatline 2.5.1): http://wired.dukedh.org/omeka/neatline/fullscreen/geoserver-test. I double checked that I wasn't accidentally changing the address or layer names when copy and pasting, so both should contain exactly the same WMS info.

Hopefully I'm making a silly mistake somewhere in here that is causing the problem.

Hannah

**Comment by waynegraham** [comment]
Hi Hannah,

Can you try changing the basemap to something other than Google? I noticed that the .org version is throwing a `RetiredVersion` warning. We need to investigate a bit further, but this may be due to #386. 

Wayne

**Comment by hlj24** [comment]
Hi Wayne,

All of the examples have OpenStreetMap listed as their basemap.

All best,

Hannah

**Comment by jamiefolsom** [comment]
Closed by #413
