### ISSUE TITLE
Neatline running super slow...

### ISSUE THREAD

**Issue by asmartinez** [performant-software/Neatline#402]
anyone have ideas as to what could be going on.  We have about 1000 records on it.

http://zapatavive.colmex.mx/neatline/show/cronologia-de-batallas

asmartinez@colmex.mx

**Comment by jeremyboggs** [comment]
Offhand, @asmartinez, I think the reason its slow is that there are 1000+ records on this exhibit. We'll see if there are ways to optimize Neatline to better handle this number of records for an exhibit.

**Comment by jamiefolsom** [comment]
Thanks, @jeremyboggs and @asmartinez,

We will take a look at this. For one thing, it looks like you're loading development assets, as I see that the page is trying to load livereload.js.

As for the quantity of data, I know that the viewport filtering feature of neatline, introduced in version 1.2, was specifically designed to mitigate performance issues related to exhibits with ~10^6 records. 

Essentially, for each record, you can use the min and max zoom level settings, to constrain when it's loaded, effectively limiting how much data are retrieved for any one view. Here's a screenshot showing the part of the editing interface where you can set those limits (at the bottom of the editor sidebar under the style tab on an individual record):

<img width="308" alt="screen shot 2017-06-12 at 3 30 13 pm" src="https://user-images.githubusercontent.com/882377/27051439-1916c0c6-4f84-11e7-9e59-4d670bcfb7a3.png">

And here's video which explains how that filtering works: https://www.youtube.com/watch?v=tPofW7j_6Y0

Would you be willing to try setting upper and lower zoom limits on some sets of records, and letting us know if that helps?

Thanks!

Jamie

**Comment by asmartinez** [comment]
Thanks for this imformation, we will look at it and see if it meets our needs!

Saludos cordiales,
Alberto Santiago Martínez
Coordinador de Innovación Digital
Biblioteca Daniel Cosío Villegas<http://biblioteca.colmex.mx/>
El Colegio de México<http://www.colmex.mx/>
55 5449 3000 Ext. 2088
0445531115620
Alberto-Santiago-Martinez.com<http://alberto-s-martinez.com/>
Skype: Akatoxkatl
 [face] <https://www.facebook.com/systems.librarian>  [in] <https://mx.linkedin.com/in/alberto-martinez-a386713b>

De: Jamie Folsom [mailto:notifications@github.com]
Enviado el: lunes, 12 de junio de 2017 02:39 p. m.
Para: scholarslab/Neatline <Neatline@noreply.github.com>
CC: Alberto Santiago Martínez <asmartinez@colmex.mx>; Mention <mention@noreply.github.com>
Asunto: Re: [scholarslab/Neatline] Neatline running super slow... (#402)


Thanks, @jeremyboggs<https://github.com/jeremyboggs> and @asmartinez<https://github.com/asmartinez>,

We will take a look at this. For one thing, it looks like you're loading development assets, as I see that the page is trying to load livereload.js.

As for the quantity of data, I know that the viewport filtering feature of neatline, introduced in version 1.2, was specifically designed to mitigate performance issues related to exhibits with ~10^6 records.

Essentially, for each record, you can use the min and max zoom level settings, to constrain when it's loaded, effectively limiting how much data are retrieved for any one view. Here's a screenshot showing the part of the editing interface where you can set those limits (at the bottom of the editor sidebar under the style tab on an individual record):

[screen shot 2017-06-12 at 3 30 13 pm]<https://user-images.githubusercontent.com/882377/27051439-1916c0c6-4f84-11e7-9e59-4d670bcfb7a3.png>

And here's video which explains how that filtering works: https://www.youtube.com/watch?v=tPofW7j_6Y0

Would you be willing to try setting upper and lower zoom limits on some sets of records, and letting us know if that helps?

Thanks!

Jamie

**Comment by jeremyboggs** [comment]
@asmartinez If our suggestions didn't help resolve your issue, please let us know, and we'll reopen the issue.
