### ISSUE TITLE
Haverford Neatline documentation not appearing

### ISSUE THREAD

**Issue by eransome** [performant-software/Neatline#404]
The link from the Neatline community documentation page to the Haverford library's Neatline-on-Neatline exhibit returns a "not found" message

**Comment by jamiefolsom** [comment]
You are correct, @eransome, it appears that documentation is gone, or has moved -- is this the page had in mind: https://ds-omeka.haverford.edu/annotations/help ?

**Comment by jeremyboggs** [comment]
Closing as fixed in d9a859d92e6a9d75af9ff1e912bef1d86942ecb8.
