### ISSUE TITLE
Omeka 2.5 error

### ISSUE THREAD

**Issue by jcmundy** [performant-software/Neatline#407]
I get the following errors when I go to Neatline in Omeka 2.5.  I cannot save changes to Neatline exhibits.

Warning: Declaration of NeatlineRecord::save() should be compatible with Neatline_Row_Expandable::save($throwIfInvalid = false) in /var/www/html/plugins/Neatline/models/NeatlineRecord.php on line 10

Warning: Declaration of NeatlineExhibit::beforeSave() should be compatible with Omeka_Record_AbstractRecord::beforeSave($args) in /var/www/html/plugins/Neatline/models/NeatlineExhibit.php on line 10

**Comment by jamiefolsom** [comment]
Hi @jcmundy, I believe this is fixed in master, via #410.

**Comment by jamiefolsom** [comment]
Closing for now. There's a fix in master, which will be included in the next release.

**Comment by jcmundy** [comment]
Thank you, @jamiefolsom I was able to edit the text manually in the meantime.
