### ISSUE TITLE
Omeka items not linking to neatline

### ISSUE THREAD

**Issue by caitmckinney** [performant-software/Neatline#415]
Hi everyone,

Sorry if this is outside the scope of github--I'm not a developer but need help. I work at the Canadian Lesbian and Gay Archives and we need to hire a developer on short notice to fix our neatline/Omeka installation (http://digitalcollections.clga.ca/) Our current web developer has said that this problem is beyond the scope of their contract with us and that they don't know how to fix it. We have a group of very eager undergraduate students working on neatline exhibits this week and next, so are eager to get this issue solved. 

Here is the deal:

We are having a problem linking neatline items to Omeka items. We have imported Omeka objects to our neatline exhibit, and did not receive any error messages but when we try to attach neatline items to Omeka items, it just hangs on the search pinwheel.

Detailed steps: 
Create neatline exhibit using and Image layer
- Select “Import Items from Omeka” and “search by collection,” then selected an existing public Omeka collection and imported it. Received an “import successful” message.
- started working on the exhibit
- created a record, then tried to link the record to an Omeka item
- No omeka items appear in the search box. The “search” pin wheel just continues to spin.

If anyone knows a developer who might be able to help our organization with this problem on short notice, I can be reached at mckinneycait@gmail.com. 

Thank you!
Cait

**Comment by davidmcclure** [comment]
Hey @caitmckinney,

Sounds like some kind of bug / misconfiguration on the server. Try this - in Chrome, open up the Developer Tools (little 3-vertical-dots icon at top right > More Tools > Developer Tools), and then click on the "Console" tab. Then open up the Neatline exhibit and try to link a record to an item. Do any errors appear in the Console? Also, does this happen for all exhibits, or just one in particular?

Let me know,
-David

**Comment by jamiefolsom** [comment]
Thanks @davidmcclure!

**Comment by rondauva** [comment]
What @jamiefolsom said! Thanks @davidmcclure!

**Comment by caitmckinney** [comment]
Thanks @davidmcclure 
It's all exhibits. Here is the error I got in the console:
![screen shot 2017-05-17 at 11 43 35 am](https://cloud.githubusercontent.com/assets/28758858/26162975/405c9e1e-3af6-11e7-8ce3-95108efbd569.png)

**Comment by jamiefolsom** [comment]
Hi @caitmckinney -- both the API version warning, and the missing API key error you're showing are fixed in the most recent commits merged to the master branch. Those fixes will be released within the next couple of weeks if all goes as planned. Whether that's what's causing the trouble you're seeing I'm not sure; your thoughts on that, @davidmcclure?

**Comment by davidmcclure** [comment]
Yeah, I don't think the Google Maps thing would affect this. @caitmckinney - does the problem show up when you search for Omeka items, or when you try to save the record? Eg, is it that you click the "Search Omeka Items" dropdown, and is just says "Searching" and no items ever appear; or can you select an item, but then it hangs when you save the Neatline record?

**Comment by caitmckinney** [comment]
@davidmcclure @jamiefolsom 

It's the former situation "you click the "Search Omeka Items" dropdown, and is just says "Searching" and no items ever appear"

**Comment by davidmcclure** [comment]
Ok, sounds like it's something with Omeka's `items/browse` API, which provides the list of items. Let's try this - back in the Developer Tools, click on "Network." Then click on the "Search Omeka items" dropdown. In the Network tab, you should see a new entry that looks like:

`browse?output=omeka-xml&search=&page=1&_=XXX`

Click on that, and then open the "Response" tab in the menu that appears on the right. What does it say there?

**Comment by caitmckinney** [comment]
@davidmcclure 
Here's what it says, not sure if I've captured this the way you need.
![screen shot 2017-05-17 at 12 49 54 pm](https://cloud.githubusercontent.com/assets/28758858/26165850/73f9ab96-3aff-11e7-91e8-9b28669fbd8a.png)

**Comment by davidmcclure** [comment]
@caitmckinney Can you select everything in the box and paste it in? I wonder if there's something in the item content that's messing up the parsing that Neatline does.

(Be aware that the XML output will include metadata from the items that might not be public on the site - if there's anything that you don't want to have on the open web, shoot me an email at `dclure at stanford dot edu`.)

**Comment by caitmckinney** [comment]
@davidmcclure This is all the text in the response box.

[CLGA_Omeka&Neatline problem.txt](https://github.com/scholarslab/Neatline/files/1008738/CLGA_Omeka.Neatline.problem.txt)

**Comment by Kent-Gerber** [comment]
@caitmckinney,

In the Omeka dashboard and the Neatline Plugin tab do you see that the Omeka items have been imported into the Neatline exhibit?  I had this issue and realized that I needed to enable the PHP-CLI function and point Omeka to it.  We use Reclaim hosting and here is the help article related to fixing this issue - https://community.reclaimhosting.com/t/setting-the-php-cli-path-in-omeka/231

Maybe this can help.

**Comment by caitmckinney** [comment]
Thanks @Kent-Gerber . How does one see if the omeka items have been imported? When I import, I receive a "import successful" message, but I don't know how to verify that the items have been imported beyond that. I will ask the person who manages our hosting to try the PHP-CLI function fix--thanks for the suggestion.

**Comment by Kent-Gerber** [comment]
@caitmckinney,
Here is a screenshot of the Omeka dashboard I am referencing.  I am thinking of looking at the number of items in the Neatline exhibit after you click the "Import Items" option and seeing whether it shows the number of items you expected to import.
 
![neatline import items on dashboard](https://cloud.githubusercontent.com/assets/7987141/26220196/4b9e47d2-3bd7-11e7-928d-d640d36e055e.png)

**Comment by caitmckinney** [comment]
@Kent-Gerber Thanks for the screenshot. 

In our exhibit, It only gives a count for the number of neatline items created in the exhibit (map points), not the number of imported Omeka items. Sounds like this could be our problem?

**Comment by caitmckinney** [comment]
Resolved! Turns out that the "Bagit" plugin was throwing a lot of exceptions that were affecting neatline. We don't actually use Bagit, so just uninstalled the plugin, and now neatline is working like a dream. Thanks everyone for your support.
