### ISSUE TITLE
Exhibit Settings Narrative text box does not appear

### ISSUE THREAD

**Issue by rondauva** [performant-software/Neatline#418]
Omeka 2.4 + Neatline 2.5.2
Chrome v. 55.0.2883.95 (64-bit) (Max OSX 10.12.5)

After updating to latest Neatline (2.5.2) on an Omeka 2.4.1 site, the Narrative text box on the Exhibit Settings page flashes briefly on screen (and if screen is refreshed) but disappears and is unavailable for text entry/formatting.

When I look at the developer tools in Chrome, the text area is there, but I can't interact with it at all.

Checked the site that I upgraded to Neatline 2.5.2 in Safari 10.1.1 and Firefox v.54.0 and did not see this issue. 
@jeremyboggs tested on v. 58.x of Chrome and does not have the issue.

Issue is not present in Omeka 2.4 or 2.5 with Neatline 2.5.1.

**Comment by rondauva** [comment]
Just looked at the javascript console and I'm getting a 404 on the CKEditor URL: http://workshop.neatline-uva.org/plugins/Neatline/views/shared/javascripts/dist/production/ckeditor/skins/moono/editor.css?t=FACH

**Comment by jeremyboggs** [comment]
Am wondering if this is just a caching issue; we updated the CKEditor skin to `moono-lisa` in this commit: https://github.com/scholarslab/Neatline/commit/6ca158283ba78aa4b5978416f82a76d4bc4307a2#diff-ac816a3f638d183aec54eb28919b26dbL28

**Comment by rondauva** [comment]
It was just a caching issue! Kudos to @jeremyboggs!
