### ISSUE TITLE
Way to duplicate exhibits or at least import records from one exhibit into another?

### ISSUE THREAD

**Issue by dleisawitz** [performant-software/Neatline#429]
I am looking for a way to make a copy of an exhibit in Neatline.  The reason is that I want to use the map that I have already designed to accompany one text and apply it to another text as a different exhibit.  

I've looked all around Neatline and on message boards, and I have not found a way to do this.  

Alternatively, it would work if I could simply import records from one exhibit into another.  I know that you can import items from omeka, but that does not help me since all of my exhibits and records are within Neatline.

Thank you,
Dan

**Comment by jamiefolsom** [comment]
Hi @dleisawitz, 

This is a good idea, and actually, we have some tickets open to work on this. See #145 (and #252). We're hoping to get this feature into the next release.

I am going to I close this issue as a duplicate, but if you have ideas to add to either of those tickets, please feel free to do so. 

Thanks!

Jamie

**Comment by dleisawitz** [comment]
Thank you, Jamie.

- Dan
