### ISSUE TITLE
Image-layer-only exhibits

### ISSUE THREAD

**Issue by akstuhl** [performant-software/Neatline#430]
Currently, users must select a spatial layer from a dropdown menu to serve as the base layer for a new exhibit. This means that an image layer can't be the first layer to load when the exhibit is viewed. Per #428, some users want to have exhibits where the image layer is the default view for the map — this may have been unintentionally possible prior to the last release due to an issue preventing the successful creation of Google Maps layers. Users should be able to choose to have no spatial layer as the base, or an option specifically to use the exhibit's image layer as its base in place of a spatial layer.

Related forum post: https://forum.omeka.org/t/neatline-image-layer-default-view/4333

**Comment by cturk24** [comment]
Hi--I am also experiencing this problem. I reverted to the previous Neatline version and it still isn't working, though. Any ideas?

**Comment by akstuhl** [comment]
Hi @cturk24, do you have a public link to the exhibit where you're experiencing this? It'd be helpful to see how the layers are behaving. There's another issue related to image layers and configuration settings that may be relevant to what you're seeing — the thread at https://github.com/scholarslab/Neatline/issues/399 has some solutions you might find useful if that's the case. Thanks!

**Comment by arthurian** [comment]
We're experiencing the same problem with v2.5.3 and are reverting back to v2.5.1.  The suggested solutions in #399 didn't work for us.

**Comment by jamiefolsom** [comment]
Hi @arthurian, thanks for letting us know. Would it be possible to provide a link to the exhibit you're having trouble with?

**Comment by rondauva** [comment]
I'm changing this to high priority, based on the number of contacts of people who previously were able to create exhibits with high-res images and no base layer showing. This used to work, but in the 2.5.2 release something changed. Thanks.

**Comment by akstuhl** [comment]
There's now a pull request up (#433) that addresses this and has been tested. The change to exhibit creation adds an option at the end of the spatial layers list for "None (Image or WMS as Default)" — how does that wording/UX sound to you, @rondauva?

This is on track to include in the 2.6.0 release once the changes are finalized.

**Comment by rondauva** [comment]
That sounds perfect @akstuhl. Thanks for the update!
