### ISSUE TITLE
Overlay is reimposing itself

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Neatline#434]
Andy thinks this is a timeline issue, but when one switches from the top overlay...
![screen shot 2017-08-31 at 2 57 15 pm](https://user-images.githubusercontent.com/18423533/29940267-b09aeabe-8e5c-11e7-9f95-f07c351cee65.png)
to the one below it, any movement of the  map or change in zoom causes the overlay to revert to the first.

**Comment by akstuhl** [comment]
After testing to confirm, this behavior appears to be the same as described in https://github.com/performant-software/Neatline/issues/15, which turned out to be due to overzealous event detection in the NeatlineSimile plugin.

**Comment by jamiefolsom** [comment]
Thanks @akstuhl and @SteveMarvin -- closing both this and #15 and opening an issue on NeatlineTime.
