### ISSUE TITLE
Neatline installation problem on Omeka 2.5?

### ISSUE THREAD

**Issue by emeehangsu** [performant-software/Neatline#439]
I just installed Neatline and most of the Neatline widgets but cannot get the plugins working.  I am able to put in a Google API code into the configure section of Neatline, but the Neatline tab of the dashboard returns a 404 error.

The Neatline widgets all error out in the plugin page, indicating that I need to install Neatline before they can function.

Any suggestions?

**Comment by jeremyboggs** [comment]
@emeehangsu what version of PHP are you using?

**Comment by emeehangsu** [comment]
I think I resolved the problem... changed the plugin file name from Neatline-2.6.0 to Neatline and that seemed to fix it.

For what its worth I'm using PHP 5.6.31...but I think the problem was a human error : )

**Comment by jeremyboggs** [comment]
@emeehangsu Do you mean the folder name?

**Comment by emeehangsu** [comment]
Yes - the folder name

**Comment by jeremyboggs** [comment]
Glad you got this working @emeehangsu!
