### ISSUE TITLE
Invalid controller error

### ISSUE THREAD

**Issue by shannonsdavis** [performant-software/Neatline#440]
I have installed Neatline 2.6.0 and tried both Omeka 2.3 and Omeka 2.5.1. In both cases, it looks as though the plugin installed successfully, but when I click on Neatline in the left hand menu, I get the error below. 

Invalid controller specified (exhibits)

exception ‘Zend_Controller_Dispatcher_Exception’ with message ‘Invalid controller specified (exhibits)’ in /usr/local/data/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/data/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/data/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /usr/local/data/htdocs/omeka/application/libraries/Zend/Application.php(382): Zend_Application_Bootstrap_Bootstrap->run()
#3 /usr/local/data/htdocs/omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#4 /usr/local/data/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#5 {main}

**Comment by jamiefolsom** [comment]
Hi @shannonsdavis -- thanks for the report! @akstuhl -- want to have a look at this one?

**Comment by akstuhl** [comment]
Hi @shannonsdavis, this sounds somewhat similar to a problem that another user was able to fix by changing the name of the Neatline plugin folder in their installation. Could you check that the folder in your Plugins directory is named Neatline (vs, e.g., Neatline-2.6.0)? Thank you!

**Comment by rhg65954** [comment]
I was having the exact same problem and this fixed it for me as well. Thanks so much!

**Comment by shannonsdavis** [comment]
Unfortunately that didn't wholly fix the problem. I have the directory named Neatline and when I go to plugins in the Omeka admin interface, under Neatline, it says "You have a new version of Neatline. Please upgrade!" When I click on the Upgrade button however, there's an error at the top of the page "The following error occurred while upgrading the Neatline plugin: Pre-2.0 versions of Neatline can't be upgraded directly to version 2.2. Upgrade to version 2.0 first!" I installed the latest version, so I'm not sure what I'm doing wrong. Thanks for your help.

**Comment by akstuhl** [comment]
@shannonsdavis Are you working with an existing installation of Neatline, or was the 2.6.0 version the first time you had installed the plugin? If an existing installation, do you know what version of Neatline you had last installed prior to 2.6.0? If you have an existing pre-2.0 installation with exhibits and records you want to persist, it may be the case that you need to install Neatline version 2.0 as an intermediary step to migrate the database entries correctly. If this is instead a new installation and you don't yet have any exhibits or records, I would try going to Plugins page of Omeka's admin interface, clicking Uninstall for Neatline, and then clicking Install again.

**Comment by shannonsdavis** [comment]
I didn't think we had a previous version installed, but I just installed 2.0 and then clicked Upgrade and this time it worked. When I click on Neatline in the admin interface I now get the Create An Exhibit option, so I think the problem is solved. Thank you!

**Comment by akstuhl** [comment]
@shannonsdavis Excellent! Glad to hear that worked, and thanks very much for your detailed descriptions. @rhg65954 thank you as well for reporting your success. I'll close this issue for now as the plugin folder naming has since been flagged and corrected.
