### ISSUE TITLE
404 Page Not Found in 

### ISSUE THREAD

**Issue by WhatTheDickens** [performant-software/Neatline#441]
I'm running Omeka 2.5.1 locally using MAMP 4.2.1 on MacOS. I installed and configured Neatline 2.6.0. The Neatline menu item shows up in the site navigation and the Dashboard navigation. Under Appearance > Navigation, the Neatline box is ticked, and the URL is set, by default, to `/neatline`.

But I can't create a new Neatline exhibit. When I click the Neatline menu item in the dashboard, instead of being prompted to create a new exhibit, I get a "404 Page Not Found" message. Ditto when I click the Neatline link in the site navigation, where I also get "`/neatline` is not a valid URL."

Have I failed to make some obvious required modification to the settings or the site structure?

I've uninstalled and reinstalled Neatline a few times, with no change in result.

**Comment by WhatTheDickens** [comment]
Issue resolved: The folder for the plugin must be renamed from `Neatline-some-version-number` to just `Neatline`.

**Comment by jamiefolsom** [comment]
👍 glad you got this sorted. I will make a patch release to correct this, if @jeremyboggs and @rondauva see no reason not to.
