### ISSUE TITLE
WKT syntax to add dots on the maps

### ISSUE THREAD

**Issue by JBPressac** [performant-software/Neatline#442]
Hello,
In a instance of Omeka 2.5.1 + Neatline 2.6, I tried to add a WKT corresponding to Austin (Texas) like this: `POINT(30.2711286 -97.7436994) ` where 30.2711286 = latitude and -97.7436994 = longitude. However, the blue dot on the map is located on the middle of the map, in the Atlantic Ocean, near the coast of Africa. Is this the correct WKT syntax ?
Thanks,

**Comment by akstuhl** [comment]
Hi @JBPressac, when comparing this to working WKT uses and testing it locally, I had some success  after adjusting both unit magnitude and lat/long order. When I adapt your original string to `POINT(-9774369.94 3027112.86)`, I see a point in the Gulf of Mexico. If you get a chance to test that format out, could you let us know if it appears correctly?

**Comment by JBPressac** [comment]
Hello, I have the same result, but those latitude and longitude correspond to [the city of Austin](https://fr.wikipedia.org/wiki/Austin_(Texas)#/maplink/1), how come that the point is in the ocean ? And why the latitude and longitude had to be multiplied by 100.000 ? Thanks,

**Comment by jcmundy** [comment]
@JBPressac  I think you are putting Lat and Long into the POINT() field.  You have to convert Lat/Long to WKT.  They aren't the same thing.  Try here: 
https://jaguillette.github.io/omekaSugar/coords/

**Comment by JBPressac** [comment]
Well, here was my problem: latitude and longitude could not be the parameters of the POINT, those parameters had to be calcuted. Thanks, @jcmundy. 

By the way, the latitude and longitude of a place given by Wikipedia is not accurate enought to calculate the WKT Point. For instance, Wikipedia gives -4.1927, 48.3188 (longitude, latitude) for [Locmaria-Plouzané](https://fr.wikipedia.org/wiki/Locmaria-Plouzan%C3%A9#/maplink/0) in Britany. Which those coordinates, the dot on the Neatline map is 20 kilometers too far. An another tool, the [Reed College Geocoding Application](https://rich.shinyapps.io/geocoder/) gives more accurate values: -4.64361, 48.37472 (longitude, latitude) and converts them to WKT.

I also discovered in the blog post of @jaguillette, [Make a Neatline Map Exhibit](https://jaguillette.github.io/omekaSugar/tutorial/collections/2016/09/07/make-a-neatline-exhibit.html), that the dot could also be manualy added by clicking on the map in the exhibit configuration...

Next step, bulk conversion of Lat/Long to WKT with Python...

**Comment by akstuhl** [comment]
Thank you @jcmundy for the explanation and web tool link! I'll close this issue for now but will add a note that WKT conversion could be a good topic to cover in the documentation. Thanks for providing these considerations and examples, @JBPressac
