### ISSUE TITLE
Google API script error when Geolocation plugin installed

### ISSUE THREAD

**Issue by akstuhl** [performant-software/Neatline#445]
Neatline checks whether a Google Maps API key has been set as a configuration option in the Geolocation plugin in order to avoid re-queueing the API script. However, the check ignores whether the Geolocation plugin is currently active or invoked in the current view, leading in several cases to a "google is not defined" error in the front end.

This bug was originally reported and documented by @jcmundy in the discussion of #424.

**Comment by jamiefolsom** [comment]
Makes sense @akstuhl -- thanks for tracking this down!
