### ISSUE TITLE
Omeka has encountered an error

### ISSUE THREAD

**Issue by djbdh** [performant-software/Neatline#450]
Hi all!
I'm a novice at Omeka and Neatline, but excited to use it.  When I have NeatlineSimile active and try to click on Neatline, I get a generic "Omeka has encountered an error" (with no error codes).  I noticed, when I de-activated NeatlineSimile, Neatline is back to good, and works fine.  I tried to uninstall NeatlineSimile from within Omeka, and get that same "Omeka has encountered an error".  Thus, I feel like it's tied to the Simile plugin.  Any ideas? I've done a few uninstalls and reinstalls of everything.  Thank you for any guidance! David
Neatline version is: 2.6.1 and Simile is: 2.0.4.

**Comment by jeremyboggs** [comment]
@djbdh sorry for the trouble! Can you tell us what version of Omeka you'r eusing too?

Also, if you have access, it can be helpful to turn on more descriptive error messages. Look at Omeka's documentation on [Retrieving Error Messages](http://omeka.org/classic/docs/Troubleshooting/Retrieving_Error_Messages/) and if you get something more descriptive, please share it here!

In the meantime, I'll see if I can reproduce the error on my own installation.

**Comment by djbdh** [comment]
Thanks, Jeremy, for the helpful guidance.  Perfect, I just turned on the Omeka (2.5.1 is my version) descriptive error messages.  Here's what I have:
Zend_Db_Statement_Mysqli_Exception
exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Table 'hchistor_omek1.omek_neatline_simile_exhibit_expansions' doesn't exist' in /home/hchistor/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/hchistor/public_html/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `neatlin...')
#1 /home/hchistor/public_html/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `neatlin...')
#2 /home/hchistor/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `neatlin...')
#3 [internal function]: Zend_Db_Adapter_Abstract->query(Object(Omeka_Db_Select), Array)
#4 /home/hchistor/public_html/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#5 /home/hchistor/public_html/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->__call('query', Array)
#6 /home/hchistor/public_html/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->query(Object(Omeka_Db_Select), Array)
#7 /home/hchistor/public_html/application/libraries/Omeka/Db/Table.php(281): Omeka_Db_Table->fetchObjects(Object(Omeka_Db_Select))
#8 [internal function]: Omeka_Db_Table->findBy(Array, 10, 1)
#9 /home/hchistor/public_html/application/controllers/helpers/Db.php(59): call_user_func_array(Array, Array)
#10 /home/hchistor/public_html/application/libraries/Omeka/Controller/AbstractActionController.php(128): Omeka_Controller_Action_Helper_Db->__call('findBy', Array)
#11 /home/hchistor/public_html/application/libraries/Omeka/Controller/AbstractActionController.php(128): Omeka_Controller_Action_Helper_Db->findBy(Array, 10, 1)
#12 /home/hchistor/public_html/plugins/Neatline/controllers/ExhibitsController.php(79): Omeka_Controller_AbstractActionController->browseAction()
#13 /home/hchistor/public_html/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->browseAction()
#14 /home/hchistor/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('browseAction')
#15 /home/hchistor/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#16 /home/hchistor/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#17 /home/hchistor/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#18 /home/hchistor/public_html/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#19 /home/hchistor/public_html/admin/index.php(28): Omeka_Application->run()
#20 {main}

**Comment by jeremyboggs** [comment]
@djbdh Have been meaning to leave you a message here, to say I haven't forgotten about this, but have been unable to reproduce the error on my own, in multiple environments. I'm still working on it.

Can you try to just uninstall the plugin, delete the plugin folder from the `plugins` directory, redownload it, and try reinstalling again? It seems like it didn't write the necessary tables to the database on installation.

**Comment by jeremyboggs** [comment]
@djbdh Could you confirm that the steps I suggested in March helped, or didn't?

Also, I just now noticed that the table name in your error message seems to be `omek_neatline_simile_exhibit_expansions`. The missing 'a' on 'omek' makes me wonder if there a typo...somewhere. Could you tell me the values for your database name and table prefix, in `db.ini`?

**Comment by djbdh** [comment]
Hey Jeremy - thank you!  And my apologies for the delay.  I did do a full uninstall and reinstall, and that seems to have fixed the issue. Regards, David

**Comment by jeremyboggs** [comment]
@djbdh Glad to hear it!
