### ISSUE TITLE
Trying to install Omeka2.6 and then Neatline on AWS server according to manual 

### ISSUE THREAD

**Issue by asegal20902** [performant-software/Neatline#451]
Hi. I am trying to install Omeka and then Neatline on my Amazon Web Services server for a project attempting to link timelines of photos to a map of locations
http://loc.gov/rr/print/coll/camilo-vergara-photographs.html

I am using the following manual

https://drive.google.com/file/d/0Bz1FHvEQjbvKLWNfYnFCVEVkOEU/edit

which is from 2013 and references Omeka 2.0
It seems that the Omeka folder is empty even after unzipping, and the zip file still has the files based on size
drwxr-xr-x 8 ubuntu ubuntu 4096 Feb 15 00:41 omeka-2.6
-rw-rw-r-- 1 ubuntu ubuntu 16344458 Feb 15 14:44 omeka-2.6.zip

Hence
sudo mv omeka2.6/* /var/www/html/
sudo mv omeka2.6/.htaccess /var/www/html/
sudo rm /var/www/html/index.html

merely yields an internal server error when I put in my AWS IP which should yield Omeka starting up.

BTW I am using a 2008 iMac with 4GB RAM.

If anyone could help I’d much appreciate it! I set up user permissions and configured the MySQL database and Apache as per the above manual pp.22-26.
Best Ariel Segal

**Comment by asegal20902** [comment]
I don’t understand why, after I unzipped Omeka, and I got the results that it had unzipped successfully, and all the files were “inflated”, that only an empty Omeka directory was created having about 4K in it 4096 bytes. It said that Omeka was in an archive in Omeka-2.6.zip
drwxr-xr-x 8 ubuntu ubuntu 4096 Feb 15 00:41 omeka-2.6
-rw-rw-r-- 1 ubuntu ubuntu 16344458 Feb 15 14:44 omeka-2.6.zip
The zip file still has several megabytes worth of data in it.
FWIW when I did sudo mv omeka2.6/* /var/www/html/ it did not work because there was nothing in omeka 2.6 to move.
When I moved the empty folder to /var/www/html/ and removed the index.html placeholder the empty folder did indeed come up in my directory instead of a system error :grinning:
I suspect that if Omeka 2.6 is properly in the right directory and all the other permissions are tweaked as per the manual things will start to work.
If anyone could offer suggestions as to how to get the right software in the directory, I’d much appreciate it!
Best Ariel Segal

**Comment by asegal20902** [comment]
Hi. I think that everything in Omeka 2.6 did move properly to /var/www/html/ and the files are there!
drwxr-xr-x 8 ubuntu ubuntu 4096 Feb 15 00:41 .
drwxrwxr-x 3 root webdev 4096 Mar 6 05:18 …
drwxr-xr-x 3 ubuntu ubuntu 4096 Feb 15 00:41 admin
drwxr-xr-x 13 ubuntu ubuntu 4096 Feb 15 00:41 application
-rw-r–r-- 1 ubuntu ubuntu 5590 Feb 15 00:41 bootstrap.php
-rw-r–r-- 1 ubuntu ubuntu 532 Feb 15 00:41 db.ini
drwxr-xr-x 7 ubuntu ubuntu 4096 Feb 15 00:41 files
-rw-r–r-- 1 ubuntu ubuntu 1702 Feb 15 00:41 .htaccess
-rw-r–r-- 1 ubuntu ubuntu 597 Feb 15 00:41 index.php
drwxr-xr-x 6 ubuntu ubuntu 4096 Feb 15 00:41 install
-rw-r–r-- 1 ubuntu ubuntu 35147 Feb 15 00:41 license.txt
drwxr-xr-x 5 ubuntu ubuntu 4096 Feb 15 00:41 plugins
-rw-r–r-- 1 ubuntu ubuntu 1225 Feb 15 00:41 README.md
-rw-r–r-- 1 ubuntu ubuntu 32 Feb 15 00:41 robots.txt
drwxr-xr-x 5 ubuntu ubuntu 4096 Feb 15 00:41 themes

The error log notes that

“[Wed Mar 07 05:23:14.031661 2018] [core:error] [pid 1520] [client 96.241.194.91:60390] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use ‘LimitInternalRecursion’ to increase the limit if necessary. Use ‘LogLevel debug’ to get a backtrace., referer: http://18.217.236.218/”

Reply

asegal21m  jflatnes
OK–> It looks like omeka is in the right directory [/var/www/html/ is the correct directory for current versions of ubuntu?]
Then I added myself as the “root” user following these steps
we are just going to use the root user as our default:
sudo groupadd webdev
sudo usermod a
G
webdev root
cd /var
sudo chown R
root.webdev www
sudo chmod 775 www
cd /var/www
sudo find . type
d | xargs sudo chmod 775
sudo find . type
f | xargs sudo chmod 664
sudo find files type
d | xargs sudo chmod 777
sudo find files type
f | xargs sudo chmod 666

Reply

asegal16m
Then it says

First, we need to set up a mysql database with a password for our root user (I am using “PaSsWoRd” here
again). We do this with the following command:
mysql -u root -p
You will be prompted to enter the password. This will enter us into the MySQL program, which you can tell
because the command line prompt has changed to mysql>. We are going to enter a series of commands
(being sure to have appended a semicolon to the end of each line) to set up our database for omeka.
Remember, I am using “root” as the user and “PaSsWoRd” as the password in this demo.
create database omeka;
grant all privileges on omeka.* to ‘root’@‘localhost’ identified by
’PaSsWoRd’;
flush privileges;
quit;
When I did this I got
mysql> create database omeka;
Query OK, 1 row affected (0.00 sec)

mysql> grant all privileges on omeka.* to ‘root’@‘localhost’ identified by ‘[my password]’;
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> quit;

Is this ok so far?

Reply

asegal14m
Then in db.ini
[database]
host = "localhost"
username = "root"
password = "[My password]"
dbname = "omeka"
prefix = "omeka_"
charset = “utf8”
;port = “”

Reply

asegal9m
Then I enabled sudo a2enmod rewrite.

The manual says to
"change some configuration files by entering the following commands:
sudo a2enmod rewrite
cd /etc/apache2
sudo nano apache2.conf"

I put

"# Enable mod_rewrite

RewriteEngine On
"
at the bottom of the .conf file but above

vim: syntax=apache ts=4 sw=4 sts=4 sr noet
Reply

asegal1m
Finally it said
"we now need to change another mod_rewrite file:
sudo nano /etc/apache2/sitesavailable/default
On the 11th line, we need to change “AllowOverride None” to “AllowOverride All”:"
However, that line is part of apache2.conf and no longer part of a default file as noted in
askubuntu.com
 user159
Cannot find /etc/apache2/sites-available/default when configuring Apache
apache2
asked by user159 on 08:33AM - 05 Dec 13
HOWEVER, should

<Directory /var/www/>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
be changed to /var/www/html/ ?

and I reset the apache2 database

but I still get
sudo /etc/init.d/apache2 restart
[Wed Mar 07 06:25:06.497204 2018] [core:error] [pid 1746] [client 69.41.14.233:38392] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use ‘LimitInternalRecursion’ to increase the limit if necessary. Use ‘LogLevel debug’ to get a backtrace.

**Comment by asegal20902** [comment]
Hi! It looks like I am getting somewhere!!

http://18.217.236.218/install/

actually does bring up an Omeka page :slight_smile:

which says that the mod_rewrite is not enabled.

Will try enabling mod_rewrite tonight

**Comment by jeremyboggs** [comment]
Hi @asegal20902, I hope you've gotten this to work. It seems like the issues you're running into involve Omeka itself, or at least getting it running on AWS. If you still need help with this, I suggest posting on the [Omeka Forum](https://forum.omeka.org/), if you haven't already. Am closing this issue.
