### ISSUE TITLE
neatline_exhibits_browse_default_sort filter is not called

### ISSUE THREAD

**Issue by zploskey** [performant-software/Neatline#457]
Attempting to define a filter for `neatline_exhibits_browse_default_sort` does not work. This is because of the way that Neatline sets its own default sort field and order. It is set in the controller here:

https://github.com/scholarslab/Neatline/blob/12d73cc2ceffc7ac5409a93d294385df889f43a8/controllers/ExhibitsController.php#L70-L81

Later, when the default sort filter would normally be run in `Omeka/Controller/AbstractActionController.php`, Omeka checks to see if `sort_field` is already defined, and if it is, it does not apply the filter at all.

As a workaround, you can use the `neatline_exhibits_browse_params` filter to set `sort_field` and `sort_dir`, but it would be nice if `browse_default_sort` could be used as it can for other types of Omeka records.

A more appropriate way to do this might be to override `_getBrowseDefaultSort()`, which defaults to `null`, but could be made to return `array('added', 'd')`. Even better, perhaps we just call `parent::browseAction();` first so that we don't set the default sort before plugins have a chance to run their filters as was done in this method in the collections controller in https://github.com/omeka/Omeka/commit/b2b272250142acce9a3d0d3724195eede4943079.

This is a pretty trivial fix, let me know if I should submit a PR.

**Comment by jeremyboggs** [comment]
@zploskey I'm very sorry we didn't respond to you, especially since this is a very trivial fix. Given that the Omeka team updated the Collections controller to put `parent::browseAction();` first, I think that's the better approach. If you'd still like to submit a patch for this, that'd be great! Otherwise, we can make this change ourselves and include it in our next bugfix release.

**Comment by zploskey** [comment]
@jeremyboggs Thanks for following up on this. I'll submit a patch.
