### ISSUE TITLE
Neatline for Omeka-S?

### ISSUE THREAD

**Issue by ataybe01** [performant-software/Neatline#460]
Hello,

We are running Omeka S, but we need to use a “Neatline” plug-in for our project. It looks"Neatline" is only for Omeka-Classic. Is it compatible with Omeka-S?

Thanks for your help.

**Comment by rondauva** [comment]
Hello,

As I stated on the Omeka forum, no, there is not currently a version of Neatline that is compatible with Omeka S. Our development partners at Performant Software are in the process of developing the new technology stack required, but there will not be a public release for many months.

Best,
Ronda
