### ISSUE TITLE
Neatline plug-in issue leaving extraneous osm in Coverage field? 

### ISSUE THREAD

**Issue by AmandaUCSC** [performant-software/Neatline#461]
Has anyone else run into issues with Neatline leaving “|||osm” in the Coverage field (see screenshot 1)? I can’t figure out what’s going on. If I deactivate everything, it’s still there. I uninstalled Neatline Features (which was causing an issue with Tiny MCE). We aren’t really using Neatline for anything publicly at the moment, but I don’t want to uninstall it because there’s still some things in there people were working on. Whether or not I activate it, however, I can’t get rid of that osm in the Coverage field. Not sure what’s the best way to handle this at this point considering we have 3,400+ records all with this field and that garbage in it. 

[Also posted this on Omeka forums with screenshots](https://forum.omeka.org/t/neatline-plug-in-issue-leaving-extraneous-osm-in-coverage-field/6742)

**Comment by jeremyboggs** [comment]
@AmandaUCSC Gonna close this ticket, since we're also discussing on the forums.
