### ISSUE TITLE
Google API Key, Spatial Layers not appearing

### ISSUE THREAD

**Issue by Dr-Hutchinson** [performant-software/Neatline#468]
Greetings,

Sorry if this question is elementary, but I'm having difficulty getting spatial layers to appear in Neatline for Omeka 2.6. I recently installed Neatline, registered for Google Cloud, and acquired a Google API Keyfor  Maps Javascript API.  I copy and pasted that key into the Neatline plugin configuration page. Omeka's Imagemagik settings appear correctly configured. But when I create a new exhibit for Neatline, none of the spatial layers for Google appear when I select the appropriate boxes. Could you provide some assistance on where I'm going wrong?

**Comment by rondauva** [comment]
Hi @Dr-Hutchinson,

The only thing I can think of is that you need the google base layer you want to use for your exhibits to appear in both the Enabled Spatial Layer and the Default Spatial Layer boxes in the Exhibit Settings, and the Image Layer, WMS Address, and WMS Layers should not have values filled in.

I'll chat with our developers about this, and if they have additional instructions or requests for follow up information, I'll let you know.

Thanks,
Ronda

**Comment by Dr-Hutchinson** [comment]
Ronda,

Many thanks for your quick assistance. I'm not sure what exactly I did, but I made a new Google API key, uninstalled & deleted Neatline, and reinstalled on the server. And now it works! Should have tried that first I guess. Thank you again!

**Comment by rondauva** [comment]
Fantastic! I'm so relieved that it's working for you now. Please do let us know if you encounter any further issues.
