### ISSUE TITLE
White border on edge of map tiles

### ISSUE THREAD

**Issue by jcmundy** [performant-software/Neatline#469]
I'm getting a white border on the (viewer's) right side of the map tiles that I pull in from geoserver.  They pull in correctly but a white band remains covering the right side of the map just before the tiles start over.  If I zoom in, the band remains the same width (thus covering less of the map).  Do you know what might be doing this?  We cannot replicate the error when pulling the map from geoserver into other platforms.

**Comment by rondauva** [comment]
Hi @jcmundy,

Did you find the solution to this? I'd just started looking into it and realized you'd closed the issue.

Best,
Ronda

**Comment by jcmundy** [comment]
It appears to be an OpenLayers issue.  When I changed the url to /geoserver/gwc/service/wms  instead of /geoserver/wms the band goes away.

**Comment by rondauva** [comment]
Thank you for the update!
