### ISSUE TITLE
Neatline 2.6.2 overriding default settings on upgrade

### ISSUE THREAD

**Issue by rondauva** [performant-software/Neatline#470]
from the Omeka forums, Jim McGrath reports:
 "Hi! An Omeka project we have on university servers recently upgraded Omeka and Neatline (Omeka to 2.7 and Neatline to 2.6.2). We had several Neatline exhibits created in Neatline 2.5.1, and in the latest version of Neatline:

-the base image layer is no longer the default layer. This seems to be an easy fix: it just looks like the Neatline upgrade overrode previous default settings and things were fine once I changed the Default Spatial Layer to “None” (which privileges the image layer). Just wanted to document that here in case other folks working with Neatline exhibits with image layers had noticed a change on the view of their projects. Additionally, when I’m in edit mode on exhibits, the image layer is not the default layer in this view, so I have to click to swap in the layer (minor thing, but seemed worth noting).

-The bigger issue: the records I created for these exhibits all still exist and are visible in edit view, but they are no longer visible in the public-facing versions of these exhibits. Any ideas why they might not be visible any more?"

https://forum.omeka.org/t/neatline-bug-in-2-6-2-records-no-longer-displaying-in-published-exhibits/8898?u=rondauva

**Comment by jeremyboggs** [comment]
Wondering offhand if this is an issue with migrating from Neatline 2.5 to 2.6, and not specifically a result of changes in 2.6.2. @jamiefolsom You think there's anyting in the changes you guys added that might contribute to this issue?
