### ISSUE TITLE
A Neatline Assistant

### ISSUE THREAD

**Issue by Maryvelma** [performant-software/Neatline#474]
Hello, I am well into a Neatline project but I need an assistant with some of the technical issues.  Anybody looking for paid work?  Thank you.

**Comment by jeremyboggs** [comment]
@Maryvelma If you've not already posted there, please consider posting work opportunities on the [Designer-Developer Opportunities forum](https://forum.omeka.org/c/designer-developer-opportunities) on the Omeka site.
