### ISSUE TITLE
Omeka+Neatline broken with PHP 7.2 update

### ISSUE THREAD

**Issue by rondauva** [performant-software/Neatline#475]
via the Omeka forum:

https://forum.omeka.org/t/omeka-classic-running-neatline-and-neatlight/9350

User ddimento there had a working Omeka+Neatline install (Omeka classic, Neatline, Neatlight theme, Waypoints), but when their hosting provider upgraded PHP to version 7.2, their exhibits no longer work.

**Comment by eam5** [comment]
This issue was closed in the Omeka forum 11/30/20
