### ISSUE TITLE
"New Record" button missing

### ISSUE THREAD

**Issue by jim1001** [performant-software/Neatline#478]
Using Omeka 2.7 & Neatline 2.6.3.

No "New Record" button appears - see screenshot.

![Neatline_no_new_record_button](https://user-images.githubusercontent.com/16447481/67856509-9b962b00-fb0c-11e9-9511-d0d4de2a5793.png)

We are testing a proxy system where requests go to a central machine (also holding the databases) & then are routed to a different machine holding the Omeka installation files. 

An internal server error, as shown, is seen when a value is sent via the search box. However I also see a similar error when doing the same on a different installation with same software versions but all on same machine. On that installation the "New Record" button is present. 

Any idea why the "New Record" button doesn't appear on the proxy system & how to diagnose?

Thanks.

**Comment by jim1001** [comment]
Update: my colleague spotted issue #475 which may be cause. Will post again after testing.

**Comment by jim1001** [comment]
My colleague fixed this issue. Here's what she said:

> the problem came down to the URL rewriting method in the proxy code. The suggested proxy-html output filter did its job on fixing urls for html, js and css files but the bit in Neatline that requests a list of records, is doing so by an AJAX call and is expecting JSON data in return. Unfortunately the mod_proxy_html filter was converting the JSON to an HTML document, so Neatline had no valid data. ...I’m now using mod_substitute to rewrite urls and that appears to do its job *and* pass JSON back as is.

She also said it wasn't obvious as the Neatline code didn't report the error.

**Comment by eam5** [comment]
Issue resolved
