### ISSUE TITLE
Neatline | Browse Exhibits first list item indent

### ISSUE THREAD

**Issue by jim1001** [performant-software/Neatline#481]
The first item on my Neatline | Browse Exhibits page appears indented to the middle of the screen. Happens  with theme "Thanks Roy" (current v2.5.1). Doesn't happen with themes The Daily or Big Stuff. Any suggestions how to fix? Happens with Neatline  v2.6.3 & 2.6.1.

Thanks
![Neatline_indent](https://user-images.githubusercontent.com/16447481/69191164-df7fbd00-0b19-11ea-942d-e5bca623aa03.JPG)

**Comment by eam5** [comment]
Thanks for bringing this to our attention. We'll be making some changes to the Neatline Browse Exhibits page in the future to fix this issue, but in the mean time, if you'd like to fix this on your end, enter the following css into your theme's style.css file:

```
#primary h2 .neatline {
  display:block;
  clear:both;
}
```

You can find the style.css file in the css folder within your theme folder. This should resolve the issue, but please follow up if not.

**Comment by jim1001** [comment]
Many thanks for the quick reply and fix. I tested on a dev site and it worked.

**Comment by jim1001** [comment]
Quick follow-up - can you advise on the best place in style.css to add this code so that it applies to all screen sizes.

Thanks.

**Comment by eam5** [comment]
You can paste it at the top of the style.css file, just make sure its not commented out or within another style element. It should apply to all screen sizes. If you are using Sass, you'll need to include it in the .scss file - see the Omeka documentation for more: https://omeka.readthedocs.io/en/latest/Tutorials/workingWithPublicThemes.html
