### ISSUE TITLE
Neatline does not show editor with a static image basemap.

### ISSUE THREAD

**Issue by jcmundy** [performant-software/Neatline#488]
I am having an issue with Omeka 2.7.1 and Neatline 2.6.3.  When I use a static image layer and leave the enable spatial layer blank, I get the following errors:
`TypeError: this.baseLayer is null`
and
`TypeError: this.view is undefined`
And the left panel editor does not show up (blank white), and I have to double click to get the image to show up on the right (then it shows).
If I do choose to enable a spatial layer, these errors do not show up, but the default basemap is the spatial layer not the image (despite be defined as the image in the admin).

**Comment by jcmundy** [comment]
This is where it seems to be having the error:
`"isValidLonLat": function(e) {
        var t = !1;
        if (null != e) {
            var i = this.getMaxExtent(), n = this.baseLayer.wrapDateLine && i;`

**Comment by jcmundy** [comment]
It appears to have been my image source blocking access to the image somehow.  I think I have it working now.  Thank you.

**Comment by rondauva** [comment]
Hi @jcmundy,

I'm glad that your issue turned out to be a simple fix! Apologies for our disarray leading to the long delay in addressing this with you, and thanks for your patience.

Ronda
