### ISSUE TITLE
Stamen maps not loading in Chrome

### ISSUE THREAD

**Issue by jcmundy** [performant-software/Neatline#496]
I'm getting the error ERR_CERT_COMMON_NAME_INVALID in Chrome for the stamen basemaps in Neatline in Omeka classic. They load in other browsers.

**Comment by jeremyboggs** [comment]
@jcmundy Can you share some info about your setup? I just loaded the three Stamen basemaps in the latest versions of OMeka/Neatline, in Chrome, and don't see that particular issue. Is it just with the Stamen layers, and not others?  It could be something weird with your browser, maybe a extension? Or something's up on your host maybe, and any SSL certificates you have on your site?

**Comment by jcmundy** [comment]
We're on Omeka 2.7.1 with Neatline 2.6.3.  This is the map: https://ornamentinflux.collections.carlos.emory.edu/neatline/show/culturesmap

**Comment by jcmundy** [comment]
Open Street Map loaded fine, but none of the stamen maps.

**Comment by jcmundy** [comment]
It's not loading on my Chrome or on the data entry person's Chrome, so I don't think it's an extension.

**Comment by jeremyboggs** [comment]
Yeah, it looks like something's up with SSL/HTTPS on Stamen's end. I just tried to load a single tile:

https://tile.stamen.com/watercolor/4/9/7.jpg

And I get Chrome's mildly dramatic private connection warning. I don't know that there's anything on either of our ends we can do, but if there's a way to reach out to Stamen about this issue, that would be good to do. It could just be a temporary thing they're already aware of and working to fix.

**Comment by jcmundy** [comment]
Okay, thank you.

**Comment by jcmundy** [comment]
It looks on the stamen page like they have separate urls for ssl tiles: http://maps.stamen.com/#usage-ssl  Could this be new?  Is there a way for me to edit these urls in my neatline plugin?  Thank you!

**Comment by jcmundy** [comment]
I was able to replace the url pattern in line 36905 of neatline-public.js and it is loading now.

**Comment by jeremyboggs** [comment]
@jcmundy Hmmm, thanks! I'm wondering now if they've changed their API, possibly deprecated the URLs we currently have? We'll investigate this a bit further on our end, but am glad you got it working for now!

**Comment by shane-et-al** [comment]
@jcmundy There is an identical pattern at line 36905 in neatline-editor.js that you'll probably also want to change. 

This might be a recent (or recent-ish) change by Stamen to use an edge distribution platform, but it might also be that we don't do enough testing with Omeka instances behind TLS. We'll investigate further.

**Comment by jcmundy** [comment]
Thank you so much for the information.  I think it might be recent, as we haven't noticed it on this map previously.

**Comment by shane-et-al** [comment]
We might just end up pointing all tile requests, HTTP and HTTPS, to their fastly URL. We'll have to test further. I'm going to keep this issue open for now, to remind us. If you run into further issues with the new address, please let us know.

**Comment by denseflux** [comment]
I came across this issue also.

I looked at documentation here to work on a fix #498 

http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Layer/OSM-js.html

**Comment by jeremyboggs** [comment]
Fixed in 9bed14d
