### ISSUE TITLE
Stamen layer not being rendered in public view

### ISSUE THREAD

**Issue by hafizchin** [performant-software/Neatline#501]
Hi,

I found a bug on `views/shared/javascripts/dist/production/neatline-public.js` on line **36903**. That line of code should be `.split(" ")`.

This bug causes the tiles / images not to be rendered as the resulting url is invalid

**Comment by hafizchin** [comment]
Thanks for resolving the issue

**Comment by jbfine** [comment]
Stamen toner not rendering in public view again.
